import type { PuzzleLanguage } from "@/lib/crossword/types";

/**
 * Curated word + clue banks for the Playground generator.
 *
 * These are the only source of Playground content: there is no model and no
 * network call anywhere in this feature. Every entry carries 2–3 alternative
 * clues so re-rolling the same word gives a different clue, and a 1–5
 * difficulty rating used to bias selection.
 *
 * Editorial rules (docs/authoring-guide.md): clues are 2–9 words, never
 * restate or contain the answer, and are factually true. Answers are single
 * words, 3–9 cells; French answers are uppercase and unaccented; Arabic
 * answers carry no diacritics and use natural spelling.
 *
 * Tags drive the player-facing option controls:
 *   properNoun    — a name (person, place, title, brand)
 *   abbreviation  — an acronym or shortened form
 *   sensitive     — excluded when family-friendly mode is on
 *
 * On the World War II banks: they cover the military, political, technical and
 * home-front record only. The Holocaust is deliberately absent — it belongs to
 * hand-authored, sourced puzzles in the `ww2-holocaust` collection, not to a
 * generator shuffling a word bank.
 *
 * On the fandom banks (Taylor Swift, One Direction): song titles, album names
 * and publicly reported career facts only. No lyrics, in any quantity, ever.
 */

export const PLAYGROUND_THEMES = [
  "cats",
  "dinosaurs",
  "plants",
  "coffee",
  "space",
  "anatomy",
  "games",
  "weather",
  "volcanoes",
  "greek-mythology",
  "world-war-ii",
  "general-knowledge",
  "gemstones",
  "oceans",
  "literature",
  "taylor-swift",
  "one-direction",
] as const;

export type PlaygroundTheme = (typeof PLAYGROUND_THEMES)[number];

export type WordDifficulty = 1 | 2 | 3 | 4 | 5;

export interface BankWord {
  answer: string;
  clues: string[];
  difficulty: WordDifficulty;
  /** A name: person, place, title or brand. */
  properNoun?: boolean;
  /** An acronym or a shortened form. */
  abbreviation?: boolean;
  /** Unsuitable for a family-friendly puzzle (violence, death, warfare). */
  sensitive?: boolean;
  /** Genuine spelling variants, same cell count as the answer. */
  alternatives?: string[];
  /** One factual line, shown as the answer explanation after solving. */
  note?: string;
}

type Bank = Partial<Record<PlaygroundTheme, BankWord[]>>;

const w = (
  answer: string,
  difficulty: WordDifficulty,
  ...clues: string[]
): BankWord => ({ answer, clues, difficulty });

/** Tag helpers — composable, e.g. `pn(ab(w("NASA", 2, "…")))`. */
const pn = (word: BankWord): BankWord => ({ ...word, properNoun: true });
const ab = (word: BankWord): BankWord => ({ ...word, abbreviation: true });
const sv = (word: BankWord): BankWord => ({ ...word, sensitive: true });
const alt = (word: BankWord, ...alternatives: string[]): BankWord => ({
  ...word,
  alternatives,
});
const nt = (word: BankWord, note: string): BankWord => ({ ...word, note });

/* ==========================================================================
   English
   ========================================================================== */

const EN: Bank = {
  cats: [
    w("PURR", 1, "Contented rumble", "Sound of a warm lap", "Low engine of happiness"),
    w("WHISKERS", 2, "Feelers beside a nose", "Width gauges on a face"),
    w("KITTEN", 1, "Young mouser", "Shoebox-sized pet"),
    w("CLAW", 1, "Retractable hook", "Sofa's natural enemy"),
    w("TAIL", 1, "Balance rod at the back", "It curls into a question mark"),
    w("PAW", 1, "Padded foot", "Print left in fresh snow"),
    w("FUR", 1, "Coat shed each spring", "What sticks to black trousers"),
    w("MEOW", 1, "Demand at the kitchen door", "Sound aimed at a tin opener"),
    w("TABBY", 2, "Striped coat pattern", "Most common marking"),
    w("SIAMESE", 2, "Blue-eyed breed from Thailand", "Famously talkative breed"),
    w("PERSIAN", 2, "Long-haired flat-faced breed", "Breed with a squashed nose"),
    w("CATNIP", 2, "Mint that causes rolling about", "Herb sold in cloth mice"),
    w("LITTER", 2, "Tray filler", "Also a group of newborns"),
    w("FELINE", 2, "Of the lion family", "Lithe and cat-like"),
    w("LION", 1, "Big cat with a mane", "Emblem on many crests"),
    w("TIGER", 2, "Largest striped hunter", "Big cat of the mangroves"),
    w("LYNX", 3, "Tuft-eared wild hunter", "Bobcat's northern cousin"),
    w("PROWL", 3, "Move about hunting", "Nightly patrol"),
    w("HAIRBALL", 3, "Grim gift on the rug", "Grooming by-product"),
    w("NAP", 1, "Short sleep", "Sunbeam activity"),
    w("SCRATCH", 2, "Mark left by a nail", "Favour behind the ears"),
    w("CALICO", 3, "Three-colour coat", "White, black and ginger patches"),
    w("SLEEK", 2, "Smooth and glossy", "Well-groomed look"),
  ],
  dinosaurs: [
    w("FOSSIL", 2, "Remains kept by stone", "What a quarry may yield"),
    w("RAPTOR", 2, "Swift clawed hunter", "Pack hunter of film fame"),
    w("SKULL", 1, "Bony case of a head", "Museum centrepiece"),
    w("TOOTH", 1, "Serrated find in rock", "Enamel-covered biter"),
    w("BONE", 1, "Piece of a skeleton", "What a dig turns up"),
    w("EGG", 1, "Nest deposit", "Shelled beginning"),
    w("SCALE", 2, "Plate of reptile skin", "Also a map ratio"),
    w("HERBIVORE", 2, "Leaf muncher", "Eater of ferns and cycads"),
    w("EXTINCT", 2, "Gone for good", "No longer found alive"),
    pn(w("JURASSIC", 2, "Middle of the three periods", "Age of huge long necks")),
    pn(w("TRIASSIC", 3, "First of the three periods", "Period that followed a great dying")),
    w("AMBER", 2, "Hardened tree resin", "Warm orange gemstone"),
    w("CRATER", 2, "Hollow left by impact", "Bowl on the moon"),
    w("PREDATOR", 2, "Hunter at the top", "It eats the plant eaters"),
    w("HORN", 1, "Bony spike on a head", "Rhino's front feature"),
    w("BEAK", 2, "Jaw without teeth", "Bird's hard mouth"),
    w("FEATHER", 2, "Light plume", "Quill with a soft vane"),
    w("SAUROPOD", 3, "Long-necked plant eater", "Four-legged giant of the Jurassic"),
    w("STEGOSAUR", 3, "Plated back, spiked tail", "Small-brained plate bearer"),
    w("SWAMP", 2, "Muggy wetland", "Boggy ground"),
    w("REPTILE", 2, "Cold-blooded scaly animal", "Class including crocodiles"),
    w("MUSEUM", 1, "Where the mounts stand", "Home of the glass cases"),
    w("CLAW", 1, "Curved hooked nail", "Sickle on a toe"),
  ],
  plants: [
    w("ROOT", 1, "Underground anchor", "It drinks for the whole plant"),
    w("LEAF", 1, "Green solar panel", "It falls in autumn"),
    w("STEM", 1, "Stalk carrying water up", "What a florist trims"),
    w("SEED", 1, "Packet contents", "Small parcel of a future tree"),
    w("PETAL", 1, "Coloured part of a bloom", "What a daisy game plucks"),
    w("POLLEN", 2, "Dust carried by bees", "Cause of a summer sneeze"),
    w("SOIL", 1, "Garden medium", "Ground for a border"),
    w("FERN", 2, "Shade lover with fronds", "Feathery woodland dweller"),
    w("MOSS", 2, "Green cushion on stones", "Damp velvet on a wall"),
    w("CACTUS", 2, "Spiny desert survivor", "Windowsill plant with needles"),
    w("ORCHID", 2, "Fussy indoor bloom", "Flower with an unusual lip"),
    w("SPROUT", 2, "First shoot", "Come up from a seed"),
    w("PRUNE", 2, "Cut a shrub back", "Snip for better growth"),
    w("COMPOST", 2, "Kitchen scraps, matured", "Dark crumbly heap"),
    w("TULIP", 1, "Dutch spring bulb", "Cup-shaped border favourite"),
    w("ROSE", 1, "Thorned classic bloom", "June's garden star"),
    w("IVY", 2, "Wall-climbing creeper", "Evergreen on old brick"),
    w("BAMBOO", 2, "Fast-growing hollow grass", "Panda's meal"),
    w("NECTAR", 2, "Sweet reward for pollinators", "What bees turn into honey"),
    w("THORN", 1, "Sharp defence on a stem", "Rose's warning"),
    w("SHRUB", 2, "Low woody grower", "Hedge material"),
    w("GRAFT", 3, "Join two plants as one", "Orchard trick with a bud"),
    w("BULB", 2, "Buried food store", "Plant it in October"),
    w("SAP", 2, "Fluid rising in spring", "Source of maple syrup"),
    w("BLOOM", 1, "Come into flower", "Peak of the season"),
  ],
  coffee: [
    w("BEAN", 1, "Roasted seed", "What a grinder eats"),
    w("ROAST", 1, "Light, medium or dark", "Time spent in the drum"),
    w("ESPRESSO", 2, "Small pressured shot", "Base of a macchiato"),
    w("LATTE", 1, "Milky order", "Canvas for foam art"),
    w("MOCHA", 2, "Chocolate-tinged cup", "Port that gave a drink its name"),
    w("ARABICA", 3, "Most-grown species", "Sweeter of the two main species"),
    w("ROBUSTA", 3, "Hardier, more bitter species", "Species heavy on caffeine"),
    w("CREMA", 3, "Tan foam on a shot", "Sign of a fresh extraction"),
    w("GRINDER", 2, "Burr machine", "It turns seeds to powder"),
    w("FILTER", 1, "Paper cone insert", "It holds back the grounds"),
    w("KETTLE", 1, "Water boiler", "Gooseneck pourer"),
    w("BARISTA", 2, "Craftsperson at the bar", "Person who pulls shots"),
    w("CAFFEINE", 2, "Morning stimulant", "Reason for the second cup"),
    w("BREW", 1, "Make a hot drink", "Let it steep"),
    w("STEAM", 1, "Jet that froths milk", "Wand's output"),
    w("MUG", 1, "Handled vessel", "Office desk staple"),
    w("FROTH", 2, "Bubbly milk top", "Airy layer"),
    w("DECAF", 2, "Evening-friendly version", "Version without the kick"),
    w("AROMA", 2, "Smell that wakes a kitchen", "First thing after grinding"),
    w("BITTER", 1, "Not sweet at all", "Over-extracted taste"),
    w("CREAM", 1, "Dairy pour", "Rich addition"),
    w("SUGAR", 1, "Sweetener cube", "Two lumps, please"),
    pn(w("ETHIOPIA", 3, "Where the drink began", "Home of the Yirgacheffe region")),
    w("SIPHON", 4, "Vacuum brewer", "Glass globes and a flame"),
    w("TAMPER", 3, "Puck presser", "Flat disc on a handle"),
  ],
  space: [
    w("ORBIT", 1, "Path around a star", "Where a station circles"),
    w("COMET", 2, "Icy visitor with a tail", "Halley's kind of body"),
    w("MOON", 1, "Cause of the tides", "First place we walked on"),
    pn(w("MARS", 1, "Rusty neighbour", "World of Olympus Mons")),
    pn(w("VENUS", 2, "Hottest planet", "World with a runaway greenhouse")),
    pn(w("SATURN", 1, "Ringed giant", "Sixth from the sun")),
    pn(w("JUPITER", 1, "Largest planet", "Host of a great red storm")),
    w("GALAXY", 1, "Billions of stars together", "Spiral of the night sky"),
    w("NEBULA", 2, "Cloud where stars form", "Glowing gas in Orion"),
    w("ROCKET", 1, "Launch vehicle", "It leaves on a column of fire"),
    w("LUNAR", 2, "Of our natural satellite", "Kind of eclipse in a full phase"),
    w("ECLIPSE", 2, "Passage into shadow", "Brief midday dusk"),
    w("ASTEROID", 2, "Wanderer of the belt", "Rocky body between two planets"),
    w("METEOR", 2, "Streak in a night sky", "Wish-worthy flash"),
    w("SOLAR", 1, "Of our own star", "Kind of wind from the sun"),
    w("GRAVITY", 1, "Pull towards mass", "Why apples fall"),
    w("TELESCOPE", 1, "Tube for stargazing", "Galileo's instrument"),
    w("SATELLITE", 2, "Circling machine", "It relays a broadcast"),
    w("CRATER", 2, "Bowl left by an impact", "Pockmark on a moon"),
    w("QUASAR", 4, "Brilliant distant beacon", "Very active galactic core"),
    w("PULSAR", 4, "Spinning radio lighthouse", "Neutron star with a beam"),
    w("COSMOS", 2, "Everything, at large", "Sagan's subject"),
    w("STAR", 1, "Distant nuclear furnace", "Point of light at night"),
    pn(w("APOLLO", 2, "Programme that reached the moon", "Missions numbered to seventeen")),
    pn(w("MERCURY", 2, "Closest to the sun", "Smallest of the eight")),
    pn(ab(w("NASA", 2, "US civil space agency, in brief", "Agency founded in 1958"))),
  ],
  anatomy: [
    w("HEART", 1, "Pump in the chest", "Four-chambered muscle"),
    w("LUNG", 1, "Organ full of air sacs", "One of a breathing pair"),
    w("LIVER", 1, "Largest internal organ", "It processes what we drink"),
    w("SPLEEN", 2, "Blood filter near the stomach", "Organ once blamed for bad moods"),
    w("KIDNEY", 1, "Bean-shaped filter", "One of a pair in the back"),
    w("FEMUR", 2, "Longest bone", "Thigh's support"),
    w("TIBIA", 2, "Shin bone", "Larger bone below a knee"),
    w("SPINE", 1, "Stack of vertebrae", "Column down the back"),
    w("NERVE", 1, "Signal fibre", "Path of a reflex"),
    w("ARTERY", 2, "Vessel carrying oxygen-rich blood", "Aorta, for one"),
    w("VEIN", 1, "Vessel of the return trip", "Where a needle goes"),
    w("MUSCLE", 1, "Tissue that contracts", "Biceps, for one"),
    w("TENDON", 2, "Cord anchoring muscle", "Achilles' famous one"),
    w("CARTILAGE", 3, "Springy padding in a joint", "Rubbery tissue of an ear"),
    w("RETINA", 2, "Layer that catches light", "Rods and cones live here"),
    w("CORNEA", 2, "Clear front of an eye", "Window over an iris"),
    w("CEREBRUM", 3, "Largest part of the brain", "Seat of thought"),
    w("PANCREAS", 2, "Source of insulin", "Gland behind the stomach"),
    w("STOMACH", 1, "Acid bag", "Where digestion gets going"),
    w("MARROW", 2, "Soft centre of a bone", "Where blood cells are made"),
    w("ENAMEL", 2, "Hardest coating in the body", "Outer shell of a tooth"),
    w("PELVIS", 2, "Hip girdle", "Basin of bone"),
    w("ELBOW", 1, "Hinge of an arm", "Joint you lean on"),
    w("RIB", 1, "Bar of the chest cage", "One of twelve pairs"),
    w("SKIN", 1, "Largest organ of all", "Barrier that sheds daily"),
    ab(w("DNA", 2, "Inheritance molecule, in brief", "Double helix, for short")),
  ],
  games: [
    w("LEVEL", 1, "Stage to clear", "It ends with a flag or a door"),
    w("BOSS", 1, "Foe at the end of a stage", "Health bar across the screen"),
    w("QUEST", 1, "Task from a stranger", "Marker on a map"),
    w("AVATAR", 2, "On-screen stand-in", "Figure you steer"),
    w("CONSOLE", 1, "Box under a television", "Cartridge or disc reader"),
    w("JOYSTICK", 2, "Upright control", "Cabinet's tall lever"),
    w("ARCADE", 2, "Hall of coin slots", "Neon room of cabinets"),
    w("PIXEL", 1, "Tiny square of a screen", "Smallest picture unit"),
    w("SPRITE", 3, "Flat moving image", "Two-dimensional character art"),
    w("RESPAWN", 2, "Return after a loss", "Come back at a checkpoint"),
    w("PATCH", 2, "Fix delivered later", "Download that mends bugs"),
    w("SPEEDRUN", 3, "Race to the credits", "Attempt against a record time"),
    w("LOOT", 2, "Rewards dropped by a foe", "Chest contents"),
    w("SAVE", 1, "Keep your progress", "Point you return to"),
    w("CHEAT", 1, "Code that bends the rules", "Up, up, down, down entry"),
    w("LAG", 2, "Delay that ruins a match", "Enemy of a fast connection"),
    w("EMULATOR", 3, "Software mimicking old hardware", "Program that runs a classic"),
    w("CARTRIDGE", 2, "Slot-in plastic case", "What you blew on in the nineties"),
    w("SEQUEL", 1, "Numbered follow-up", "The one with a two on the box"),
    w("DEMO", 1, "Sample slice", "Free taste of a release"),
    w("SCORE", 1, "Points tally", "Number on a leaderboard"),
    pn(w("TETRIS", 2, "Falling-block classic", "Game of clearing lines")),
    w("PINBALL", 2, "Flippers and bumpers", "Table with a plunger"),
    w("CONTROL", 2, "What a pad gives you", "Steering of a character"),
  ],
  weather: [
    w("RAIN", 1, "Falling drops", "Reason for a mackintosh"),
    w("CLOUD", 1, "Grey patch overhead", "Cumulus, for one"),
    w("STORM", 1, "Violent spell", "It knocks out power lines"),
    w("THUNDER", 1, "Rumble after a flash", "Sound that follows light"),
    w("FROST", 1, "White coating at dawn", "Gardener's spring worry"),
    w("SNOW", 1, "Winter flakes", "Reason for a sledge"),
    w("HAIL", 1, "Ice pellets", "Pea-sized fall that dents cars"),
    w("WIND", 1, "Moving air", "It turns a turbine"),
    w("BREEZE", 1, "Gentle current of air", "Pleasant coastal air"),
    w("GALE", 2, "Very strong blow", "Force eight"),
    w("FOG", 1, "Very low visibility", "Reason for a horn at sea"),
    w("MIST", 1, "Fine damp haze", "Morning veil over a field"),
    w("HUMID", 2, "Sticky and damp", "Sultry, in a word"),
    w("DROUGHT", 2, "Long dry spell", "Cause of a hosepipe ban"),
    w("MONSOON", 2, "Seasonal rains", "Wet half of a tropical year"),
    w("TORNADO", 1, "Twisting funnel", "It touches down on a plain"),
    w("CYCLONE", 2, "Spiralling system", "What a hurricane is called elsewhere"),
    w("BAROMETER", 2, "Pressure gauge", "Instrument with a needle and a dial"),
    w("FORECAST", 1, "Tomorrow's outlook", "The evening bulletin"),
    w("RAINBOW", 1, "Arc after a shower", "Seven-banded sight"),
    w("SLEET", 2, "Half-frozen fall", "Neither one thing nor the other"),
    w("DEW", 1, "Dawn moisture on grass", "It leaves a point in its name"),
    w("HEATWAVE", 2, "Long hot stretch", "Spell that melts tarmac"),
    w("ISOBAR", 4, "Line of equal pressure", "Chart curve of a low"),
    w("LIGHTNING", 1, "Electric flash", "It seeks the tallest point"),
  ],

  volcanoes: [
    nt(
      w("LAVA", 1, "Molten rock at the surface", "It cools into dark stone"),
      "Lava is magma once it has reached the surface; the name changes with the location, not the material."
    ),
    w("MAGMA", 2, "Molten rock still underground", "Contents of a chamber below"),
    w("CRATER", 1, "Bowl at a summit", "Hollow above a vent"),
    nt(
      w("CALDERA", 3, "Basin left by a collapse", "Wide hollow ringed by cliffs"),
      "A caldera forms when the roof of an emptied chamber founders, so it is wider than the vent that made it."
    ),
    w("ASH", 1, "Grey fall that grounds flights", "Fine airborne fragments"),
    w("VENT", 2, "Opening that lets gas escape", "Mouth of a fissure"),
    nt(
      w("PUMICE", 3, "Rock light enough to float", "Frothy stone used to scrub"),
      "Pumice is glass full of gas bubbles, which is why it floats until the pores fill."
    ),
    w("BASALT", 2, "Dark fine-grained rock", "Stone of the Giant's Causeway"),
    w("OBSIDIAN", 3, "Volcanic glass, jet black", "Rock once knapped into blades"),
    pn(nt(
      w("ETNA", 2, "Sicilian mountain, often active", "Tallest active peak in Europe"),
      "Etna has been in near-continuous activity for decades and is monitored constantly."
    )),
    pn(nt(
      w("VESUVIUS", 3, "Mountain above the Bay of Naples", "It buried Pompeii in 79 CE"),
      "The 79 CE eruption is described in two letters by Pliny the Younger."
    )),
    pn(w("KRAKATOA", 3, "Indonesian island of an 1883 blast", "Site of a famously loud eruption")),
    pn(w("ICELAND", 2, "Island astride a spreading ridge", "North Atlantic land of fissures")),
    w("FISSURE", 3, "Long crack that erupts", "Split feeding a curtain of fire"),
    w("ERUPTION", 2, "What ends a dormant spell", "Event rated on the VEI scale"),
    w("DORMANT", 2, "Quiet, but not finished", "Between two active spells"),
    w("PLUME", 3, "Rising column of hot mantle", "Deep source under a hotspot"),
    w("CONE", 1, "Shape built by layered ejecta", "Classic mountain profile"),
    nt(
      w("LAHAR", 4, "Volcanic mudflow", "Ash and water rushing downhill"),
      "Lahars often do more damage than lava, because they travel fast and far down river valleys."
    ),
    w("TEPHRA", 4, "Fragments thrown out by a blast", "Airborne debris, collectively"),
    w("SULPHUR", 2, "Yellow crust around a vent", "Element behind the sharp smell"),
    w("GEYSER", 2, "Hot spring that spouts", "Steam jet on a rough schedule"),
    w("SHIELD", 3, "Broad, gently sloping type", "Form of Mauna Loa"),
    w("RIFT", 2, "Where plates pull apart", "Valley of a spreading zone"),
    w("SEISMIC", 3, "Of earth tremors", "Kind of swarm before a blast"),
    w("MANTLE", 2, "Layer beneath the crust", "Source of the melt"),
  ],

  "greek-mythology": [
    pn(w("ZEUS", 1, "King of the Olympian gods", "Wielder of the thunderbolt")),
    pn(w("HERA", 2, "Queen of the Olympians", "Goddess of marriage")),
    pn(w("HADES", 2, "Ruler of the underworld", "Brother who drew the worst lot")),
    pn(w("ATHENA", 1, "Goddess of wisdom and craft", "Patron of a great city")),
    pn(w("APOLLO", 1, "God of music and prophecy", "Owner of the Delphic shrine")),
    pn(w("ARTEMIS", 2, "Goddess of the hunt", "Twin sister of a sun god")),
    pn(w("HERMES", 2, "Messenger with winged sandals", "Guide of souls downward")),
    pn(w("ARES", 2, "God of battle", "Counterpart of a Roman war god")),
    pn(nt(
      w("ICARUS", 2, "Boy who flew too high", "Son of a Cretan craftsman"),
      "The wings were his father Daedalus's work; the wax that held them melted near the sun."
    )),
    pn(w("MEDUSA", 2, "Gorgon with a stony stare", "Snake-haired figure of the myth")),
    pn(w("MINOTAUR", 2, "Bull-headed dweller of a maze", "Beast kept beneath Knossos")),
    w("LABYRINTH", 3, "Maze built for a king of Crete", "Winding prison of the myth"),
    pn(w("OLYMPUS", 2, "Home of the twelve", "Highest mountain in Greece")),
    pn(w("ODYSSEY", 2, "Ten-year voyage home", "Second of Homer's epics")),
    pn(w("ILIAD", 3, "Epic of a ten-year siege", "First of Homer's epics")),
    pn(w("TROJAN", 2, "Of the besieged city", "Kind of horse in the tale")),
    w("ORACLE", 2, "Voice consulted at a shrine", "Riddling answer from a god"),
    pn(w("DELPHI", 3, "Sanctuary on Mount Parnassus", "Seat of a famous prophetess")),
    w("TITAN", 2, "Elder god of the earlier age", "One defeated by the Olympians"),
    w("CHIMERA", 3, "Fire-breathing hybrid beast", "Lion, goat and serpent in one"),
    w("HYDRA", 3, "Many-headed serpent of Lerna", "It grew two for each one lost"),
    pn(w("PEGASUS", 2, "Winged horse of the myth", "Mount of Bellerophon")),
    w("CENTAUR", 2, "Half-horse of the mountains", "Chiron was one"),
    w("SIREN", 2, "Singer who lured sailors", "Voice to be tied to a mast against"),
    w("NECTAR", 2, "Drink of the immortals", "What the gods sipped"),
    w("AMBROSIA", 3, "Food of the immortals", "Divine fare of the myth"),
    w("CYCLOPS", 2, "One-eyed giant", "Shepherd blinded by Odysseus"),
    w("MUSE", 2, "One of nine inspirers", "Source a poet invokes"),
    alt(pn(w("HERACLES", 3, "Hero of the twelve labours", "Strong man of the myth")), "HERAKLES"),
    pn(w("STYX", 3, "River crossed by the dead", "Water gods swore by")),
  ],

  "world-war-ii": [
    w("ALLIES", 1, "Coalition including Britain and the USSR", "Side that accepted the surrenders"),
    w("AXIS", 1, "Germany, Italy and Japan together", "Side defeated in 1945"),
    pn(nt(
      w("NORMANDY", 2, "Region of the June 1944 landings", "Coast of Operation Overlord"),
      "The landings began on 6 June 1944 across five beaches in northern France."
    )),
    pn(w("DUNKIRK", 2, "Port of the 1940 evacuation", "Beaches cleared by small boats")),
    pn(w("BLITZ", 2, "Bombing of British cities, 1940-41", "Nights spent in shelters")),
    pn(nt(
      w("ENIGMA", 2, "German cipher machine", "Rotor device read by codebreakers"),
      "Polish cryptanalysts broke early Enigma traffic before the work moved to Britain in 1939."
    )),
    pn(w("BLETCHLEY", 3, "Buckinghamshire codebreaking site", "Home of Hut 8")),
    ab(w("RADAR", 2, "Detection by radio echoes", "Early-warning system of 1940")),
    w("CONVOY", 2, "Merchant ships under escort", "Atlantic formation against submarines"),
    w("RATION", 1, "Fixed allowance of food", "What a coupon book allowed"),
    pn(w("TOBRUK", 3, "Libyan port under long siege", "Objective in the desert campaign")),
    pn(nt(
      w("ALAMEIN", 3, "Egyptian rail halt of 1942 battles", "Turning point in North Africa"),
      "The second battle there ran from October to November 1942 and ended the Axis advance on Egypt."
    )),
    pn(w("MIDWAY", 2, "Pacific atoll, June 1942", "Carrier battle north-west of Hawaii")),
    pn(w("OKINAWA", 3, "Island fought over in 1945", "Last great Pacific land battle")),
    pn(w("ARDENNES", 3, "Forest of a 1944 counter-offensive", "Wooded ground held in winter")),
    pn(w("YALTA", 3, "Crimean conference of February 1945", "Meeting of the three leaders")),
    pn(w("POTSDAM", 3, "Conference of July 1945", "Talks held outside Berlin")),
    w("MAQUIS", 4, "French rural resistance bands", "Fighters of the scrubland"),
    w("PARTISAN", 3, "Irregular fighter behind the lines", "Member of an underground band"),
    pn(w("SPITFIRE", 2, "British single-seat fighter", "Aircraft with elliptical wings")),
    pn(w("LANCASTER", 3, "British four-engine bomber", "Heavy aircraft of 1942 onward")),
    sv(w("BOMBER", 2, "Aircraft built to attack from above", "Type escorted by fighters")),
    sv(w("TORPEDO", 2, "Self-propelled underwater weapon", "Launched from a submarine")),
    sv(w("SIEGE", 2, "Encirclement to force surrender", "Long blockade of a city")),
    sv(w("CASUALTY", 3, "Person killed or wounded", "Figure in a grim tally")),
    w("SURRENDER", 3, "Formal end of the fighting", "What was signed in May 1945"),
    w("JEEP", 2, "Light four-wheel-drive vehicle", "Utility car of the campaigns"),
    w("BUNKER", 2, "Reinforced shelter", "Concrete refuge underground"),
    w("CURFEW", 2, "Order to stay in after dark", "Rule enforced under occupation"),
    w("BLACKOUT", 2, "Rule against showing light", "Why windows were curtained"),
    pn(w("CHURCHILL", 3, "British prime minister from 1940", "Leader of the wartime coalition")),
    pn(w("VICHY", 3, "French regime seated at a spa town", "Government of 1940 to 1944")),
  ],

  "general-knowledge": [
    pn(w("PARIS", 1, "Capital on the Seine", "City of the Louvre")),
    pn(w("EVEREST", 2, "Highest peak above sea level", "Summit on a Nepal border")),
    pn(w("NILE", 2, "River through Cairo", "Long river of north-east Africa")),
    pn(w("SAHARA", 2, "Largest hot desert", "Sand across northern Africa")),
    w("OXYGEN", 2, "Element numbered eight", "Gas needed to breathe"),
    w("IRON", 1, "Metal that rusts", "Element of a smith's trade"),
    w("PIANO", 1, "Instrument with eighty-eight keys", "Upright or grand"),
    w("VIOLIN", 2, "Four strings and a bow", "Smallest of the string family"),
    w("OCTAGON", 3, "Eight-sided figure", "Shape of a stop sign"),
    w("ATLAS", 2, "Book of maps", "Reference full of borders"),
    w("COMPASS", 2, "It points to magnetic north", "Hiker's needle"),
    pn(w("MOZART", 2, "Composer of The Magic Flute", "Salzburg-born prodigy")),
    pn(w("HAMLET", 3, "Danish prince of a tragedy", "Role with a graveyard scene")),
    w("PYRAMID", 2, "Tomb shape at Giza", "Square base, four faces"),
    w("MARATHON", 2, "Race of forty-two kilometres", "Long event closing the Games"),
    w("CENTURY", 1, "Hundred years", "Also a batsman's hundred"),
    w("DECADE", 1, "Ten years", "Span of the nineties"),
    w("ALPHABET", 2, "Ordered set of letters", "What a primer teaches"),
    pn(ab(w("UNESCO", 3, "UN body for education and culture", "It keeps a World Heritage list"))),
    ab(w("ATM", 2, "Cash machine, in brief", "Hole in the wall, for short")),
    w("HELIUM", 2, "Gas that lifts balloons", "Second element on the table"),
    w("PENGUIN", 1, "Flightless bird of the far south", "Swimmer in a dinner jacket"),
    w("KANGAROO", 2, "Marsupial that hops", "Animal with a pouch"),
    pn(w("SPAIN", 1, "Country of the Prado", "Land west of the Pyrenees")),
    pn(w("TOKYO", 2, "Capital of Japan", "Host city of the 1964 Games")),
    w("CHESS", 1, "Game on sixty-four squares", "Board with two bishops each"),
    w("VITAMIN", 2, "Nutrient needed in small amounts", "C or D, for example"),
    w("GLACIER", 3, "River of slow ice", "It carves a U-shaped valley"),
  ],

  gemstones: [
    w("RUBY", 1, "Red stone of the corundum family", "July's birthstone"),
    w("EMERALD", 2, "Green beryl", "Stone of Colombian mines"),
    w("SAPPHIRE", 2, "Blue corundum", "September's birthstone"),
    w("DIAMOND", 1, "Hardest natural mineral", "Stone cut into brilliants"),
    w("OPAL", 2, "Stone with a shifting play of colour", "Australian speciality"),
    w("TOPAZ", 2, "Golden silicate stone", "November's birthstone"),
    w("GARNET", 2, "Deep red silicate group", "January's birthstone"),
    w("AMBER", 2, "Fossil resin", "It sometimes traps an insect"),
    w("JADE", 2, "Green stone carved in China", "Nephrite or jadeite"),
    w("PEARL", 1, "Gem grown inside a shell", "Layer on layer of nacre"),
    w("QUARTZ", 2, "Commonest silicate mineral", "It keeps time in a watch"),
    w("AGATE", 3, "Banded chalcedony", "Stone sliced to show rings"),
    w("ONYX", 3, "Black banded stone", "Dark stone of a signet ring"),
    w("CARAT", 2, "Gem weight of 200 milligrams", "Unit on a jeweller's scale"),
    w("FACET", 2, "One flat face of a cut stone", "Polished plane"),
    w("TURQUOISE", 3, "Sky-blue copper mineral", "Stone set in silver by Navajo makers"),
    w("AMETHYST", 2, "Purple variety of a common mineral", "February's birthstone"),
    w("ZIRCON", 3, "Mineral used to date old rock", "Stone often mistaken for a brilliant"),
    w("PERIDOT", 4, "Olive-green olivine gem", "August's birthstone"),
    w("CORAL", 2, "Skeleton worn as a bead", "Pink material from a reef"),
    pn(w("MOHS", 4, "Hardness scale of ten steps", "Scale from talc to diamond")),
    w("LAPIS", 3, "Deep blue stone of Afghanistan", "Source of an old ultramarine"),
    w("CAMEO", 3, "Relief carved in a layered stone", "Portrait brooch"),
    w("BRILLIANT", 3, "Round cut with fifty-seven faces", "Cut that maximises fire"),
    w("CLARITY", 3, "One of the four Cs", "Freedom from internal flaws"),
    w("INCLUSION", 4, "Foreign matter inside a stone", "Flaw sealed in as it grew"),
    w("MINERAL", 1, "Naturally occurring solid", "What a gem is, before cutting"),
  ],

  oceans: [
    w("CORAL", 1, "Reef builder in warm water", "Colony of tiny polyps"),
    w("REEF", 1, "Ridge under shallow water", "Structure off Queensland"),
    w("WHALE", 1, "Largest animal alive", "Mammal that surfaces to breathe"),
    w("DOLPHIN", 1, "Clicking mammal of the bow wave", "Toothed swimmer in pods"),
    w("OCTOPUS", 2, "Eight-armed hunter", "Animal with three hearts"),
    w("SQUID", 2, "Ten-armed relative of an octopus", "Prey of a sperm whale"),
    w("KELP", 2, "Brown seaweed forest", "Holdfast, stipe and blade"),
    w("PLANKTON", 2, "Drifting life of the surface", "Base of the marine food web"),
    w("TIDE", 1, "Twice-daily rise and fall", "Pull of a moon on water"),
    w("CURRENT", 2, "Steady flow through the sea", "The Gulf Stream is one"),
    w("TRENCH", 2, "Deepest kind of sea floor", "Long gash where plates dive"),
    w("ABYSS", 3, "Depths without sunlight", "Zone below a thousand metres"),
    w("LAGOON", 2, "Water enclosed by a reef", "Shallow pool inside an atoll"),
    w("SHARK", 1, "Cartilage-skeletoned hunter", "Fish with rows of spare teeth"),
    w("MANTA", 3, "Ray with wing-like fins", "Filter feeder of warm seas"),
    w("TURTLE", 1, "Shelled reptile that nests on sand", "Long-lived ocean traveller"),
    w("ANEMONE", 3, "Stinging flower of the rocks", "Host to a clownfish"),
    w("URCHIN", 2, "Spiny grazer of the sea bed", "Ball of purple spines"),
    w("MUSSEL", 2, "Bivalve on a rope", "Shellfish steamed in wine"),
    w("SALINITY", 3, "Salt content of water", "Measured in parts per thousand"),
    w("ESTUARY", 3, "Where a river meets the sea", "Brackish mouth of a river"),
    w("MANGROVE", 3, "Tree with roots in salt water", "Nursery for young fish"),
    w("TSUNAMI", 2, "Wave train from a sea-floor jolt", "Long wave that shallows into a wall"),
    pn(w("PACIFIC", 1, "Largest ocean", "Water between Asia and the Americas")),
    pn(w("MARIANA", 4, "Trench of the deepest known point", "Feature east of the Philippines")),
    ab(w("SONAR", 3, "Echo ranging at sea, in brief", "How a ship reads the bottom")),
    w("BALEEN", 4, "Filter plates in a whale's mouth", "Keratin comb of a rorqual"),
    w("KRILL", 2, "Small crustacean eaten by whales", "Swarming shrimp of cold seas"),
  ],

  "taylor-swift": [
    pn(nt(
      w("FEARLESS", 2, "Second studio album, 2008", "Record with a re-recorded version"),
      "It won Album of the Year at the 2010 Grammy Awards."
    )),
    pn(w("RED", 2, "Fourth studio album, 2012", "One-word album title of 2012")),
    pn(w("LOVER", 2, "Seventh studio album, 2019", "Album released in August 2019")),
    pn(nt(
      w("FOLKLORE", 2, "Album released in July 2020", "Quieter record made in lockdown"),
      "Announced hours before release, it took Album of the Year at the 2021 Grammy Awards."
    )),
    pn(w("EVERMORE", 3, "Companion album of December 2020", "Second surprise album of that year")),
    pn(w("MIDNIGHTS", 2, "Album released in October 2022", "Record of thirteen sleepless tales")),
    pn(w("CARDIGAN", 3, "Lead single from a 2020 album", "Single released in July 2020")),
    pn(w("WILLOW", 3, "Opening track of a 2020 companion album", "Single of December 2020")),
    pn(w("ANTIHERO", 3, "Lead single from a 2022 album", "Single with a much-quoted bridge")),
    pn(w("BEJEWELED", 4, "Single from a 2022 album", "Track with a Nutcracker-styled video")),
    pn(nt(
      w("MEAN", 3, "Country single of 2010", "Track that won two Grammy Awards"),
      "It won Best Country Song and Best Country Solo Performance in 2012."
    )),
    pn(w("ERAS", 2, "Name of the 2023 stadium tour", "Tour built around every album")),
    pn(w("GRAMMY", 2, "Award she has won for Album of the Year", "Trophy shaped like a gramophone")),
    pn(w("NASHVILLE", 3, "City she moved to as a teenager", "Home of the country industry")),
    pn(w("READING", 3, "Pennsylvania city near her birthplace", "Town in Berks County")),
    pn(ab(w("BMI", 4, "US songwriter royalty body, in brief", "Performing-rights group, for short"))),
    pn(w("BILLBOARD", 3, "US chart publication", "Magazine of the Hot 100")),
    w("ALBUM", 1, "Studio collection of songs", "What a tour is often built around"),
    w("SINGLE", 1, "Track released on its own", "First taste of a record"),
    w("TOUR", 1, "Run of shows city by city", "What a stadium run is called"),
    w("STADIUM", 2, "Venue of her largest shows", "Ground that seats tens of thousands"),
    w("VAULT", 3, "Where unreleased tracks came from", "Word she uses for shelved songs"),
    w("COUNTRY", 2, "Genre of her earliest records", "Nashville's own genre"),
    w("POP", 1, "Genre she moved to by 2014", "Chart-facing style"),
    w("GUITAR", 1, "Instrument she plays on stage", "Six strings and a strap"),
    w("DIRECTOR", 3, "Role she took on her own videos", "Person who calls the shots on set"),
    w("SINGER", 1, "What she is, by trade", "Person at the microphone"),
    w("ENCORE", 2, "Extra song after the set", "What the shouting is for"),
  ],

  "one-direction": [
    pn(nt(
      w("XFACTOR", 2, "Talent show where the group formed", "Programme that put five soloists together"),
      "The five auditioned separately in 2010 and were placed in a group at the judges' houses stage."
    )),
    pn(w("COWELL", 3, "Judge who put the group together", "Founder of their first label")),
    pn(w("STYLES", 2, "Surname of the Cheshire-born member", "Later a solo act with three albums")),
    pn(w("HORAN", 3, "Surname of the Irish member", "Member from County Westmeath")),
    pn(w("PAYNE", 3, "Surname of the Wolverhampton member", "One of the five, born in 1993")),
    pn(w("MALIK", 3, "Surname of the Bradford member", "Member who left in 2015")),
    pn(w("TOMLINSON", 3, "Surname of the Doncaster member", "Member with a football sideline")),
    pn(w("FOUR", 2, "Fourth studio album, 2014", "Album titled with a number")),
    pn(w("IRELAND", 2, "Country one member comes from", "Island west of Great Britain")),
    pn(w("LONDON", 1, "City where the group was formed", "Capital of their first auditions")),
    pn(w("WEMBLEY", 3, "London stadium they headlined", "Venue with a famous arch")),
    pn(ab(w("BRIT", 3, "British music award, in short", "Prize they won twice"))),
    w("HIATUS", 3, "Break the group began in 2016", "Pause with no announced end"),
    w("BOYBAND", 1, "Category of group they belong to", "Five singers, no instruments required"),
    w("QUINTET", 3, "Group of five performers", "Five-piece, formally"),
    w("SOLO", 2, "How each career continued", "On one's own"),
    w("ALBUM", 1, "Studio collection of songs", "Release numbered in a discography"),
    w("SINGLE", 1, "Track released on its own", "What a chart position measures"),
    w("DEBUT", 2, "First release of a career", "The one before the follow-up"),
    w("CHART", 1, "Weekly ranking of sales and plays", "Table topped by a hit"),
    w("TOUR", 1, "Run of shows city by city", "What sells out in an hour"),
    w("ARENA", 2, "Large indoor venue", "Step below a stadium"),
    w("FANDOM", 2, "Community of devoted followers", "The people behind the trending tags"),
    w("MERCH", 3, "Shirts and posters sold on tour", "Stall by the entrance"),
    w("MANAGER", 2, "Person who runs a group's business", "Signer of the contracts"),
    w("ENCORE", 2, "Extra song after the set", "Return to the stage"),
    w("HARMONY", 2, "Voices stacked together", "What five singers can build"),
    w("STADIUM", 2, "Venue of their 2014 shows", "Ground that seats tens of thousands"),
  ],

  literature: [
    w("NOVEL", 1, "Long prose story", "Full-length work of fiction"),
    w("POEM", 1, "Verse on a page", "Short piece with deliberate line breaks"),
    w("SONNET", 2, "Fourteen-line form", "Petrarchan or Shakespearean"),
    w("STANZA", 2, "Block of lines in verse", "A poem's paragraph"),
    w("PROSE", 2, "Ordinary written language", "Everything that is not verse"),
    w("CHAPTER", 1, "Numbered division of a book", "What you read one more of"),
    w("PLOT", 1, "Sequence of events", "What happens, in order"),
    w("METAPHOR", 3, "Comparison without like or as", "Calling one thing another"),
    w("SIMILE", 3, "Comparison using like or as", "Figure with an explicit link"),
    w("IRONY", 3, "Gap between said and meant", "Saying one thing, meaning the reverse"),
    w("SATIRE", 3, "Mockery with a purpose", "Ridicule aimed at a target"),
    w("ELEGY", 4, "Lament for the dead", "Mournful poem"),
    w("FABLE", 2, "Short tale with a moral", "Animals teaching a lesson"),
    w("EPIC", 2, "Long heroic narrative", "Story told on a grand scale"),
    w("TRAGEDY", 2, "Play that ends badly", "Drama of a fatal flaw"),
    w("COMEDY", 2, "Play that ends in a wedding", "Genre meant to amuse"),
    w("NARRATOR", 3, "Voice telling the story", "The one saying I"),
    w("LIBRARY", 1, "Room of borrowed books", "Where the silence is kept"),
    w("AUTHOR", 1, "Name on the cover", "The one who wrote it"),
    w("PREFACE", 3, "Note before the first chapter", "Front matter by the writer"),
    w("ODE", 2, "Poem of praise", "Address to an urn or a bird"),
    w("HAIKU", 3, "Three-line Japanese form", "Seventeen syllables"),
    w("VERSE", 2, "Writing in metre", "Lines that scan"),
    w("RHYME", 1, "Matching sounds at line ends", "Moon and June, for instance"),
    pn(w("AUSTEN", 3, "Surname behind Emma", "Novelist of Bath drawing rooms")),
    pn(w("ORWELL", 3, "Pen name behind Animal Farm", "Essayist of Nineteen Eighty-Four")),
    pn(w("DICKENS", 3, "Surname behind Bleak House", "Serial writer of Victorian London")),
    pn(w("BRONTE", 4, "Surname of three novelist sisters", "Family of the Yorkshire moors")),
    pn(w("ODYSSEY", 3, "Homer's long voyage home", "Ten years of getting back")),
  ],
};

/* ==========================================================================
   French — answers uppercase and unaccented, clues in natural French
   ========================================================================== */

const FR: Bank = {
  cats: [
    w("CHATON", 1, "Jeune félin joueur", "Il tient dans une main"),
    w("MIAOU", 1, "Cri devant la gamelle", "Réclamation sonore"),
    w("GRIFFE", 1, "Ongle rétractile", "Ennemie du canapé"),
    w("MOUSTACHE", 2, "Poil sensible du museau", "Repère de largeur"),
    w("QUEUE", 1, "Balancier arrière", "Elle se met en point d'interrogation"),
    w("PATTE", 1, "Coussinet et ongles", "Elle laisse une empreinte"),
    w("POIL", 1, "Ce qui reste sur le pull noir", "Il tombe au printemps"),
    w("FELIN", 2, "De la famille du lion", "Souple et silencieux"),
    w("SIAMOIS", 2, "Race aux yeux bleus", "Race très bavarde"),
    w("PERSAN", 2, "Race au museau aplati", "Long pelage et face plate"),
    w("TIGRE", 1, "Grand fauve rayé", "Fauve du Bengale"),
    w("LION", 1, "Fauve à crinière", "Roi des armoiries"),
    w("LYNX", 3, "Fauve aux oreilles touffues", "Il voit très bien, dit-on"),
    w("RONRON", 1, "Petit moteur du bonheur", "Vibration de contentement"),
    w("SIESTE", 1, "Repos de l'après-midi", "Pause au soleil"),
    w("LITIERE", 2, "Bac de la maison", "Gravier parfumé du couloir"),
    w("CROQUETTE", 2, "Repas sec en granulés", "Ration du matin"),
    w("SOURIS", 1, "Proie classique", "Petit rongeur gris"),
    w("PELAGE", 2, "Robe de l'animal", "Ensemble des poils"),
    w("CHASSE", 2, "Traque nocturne", "Affût dans le jardin"),
    w("ANGORA", 3, "Race aux très longs poils", "Race venue de Turquie"),
    w("GOUTTIERE", 3, "Chat sans pedigree", "Il vient de la rue"),
    w("SAUT", 1, "Bond vers l'étagère", "Détente des pattes arrière"),
  ],
  dinosaurs: [
    w("FOSSILE", 2, "Empreinte gardée par la pierre", "Trouvaille de carrière"),
    w("CRANE", 1, "Boîte osseuse de la tête", "Pièce maîtresse du musée"),
    w("DENT", 1, "Croc retrouvé dans la roche", "Elle est couverte d'émail"),
    w("OEUF", 1, "Ce que la femelle dépose au nid", "Début sous coquille"),
    w("GRIFFE", 1, "Ongle crochu", "Faux sur un orteil"),
    w("ECAILLE", 2, "Plaque de peau de reptile", "Elle couvre le crocodile"),
    w("REPTILE", 2, "Animal à sang froid", "Classe du lézard"),
    pn(w("TRIAS", 3, "Première des trois périodes", "Elle suit une grande extinction")),
    pn(w("CRETACE", 3, "Dernière période des géants", "Elle finit par un cataclysme")),
    w("AMBRE", 2, "Résine fossilisée", "Pierre orangée et chaude"),
    w("QUEUE", 1, "Contrepoids arrière", "Elle porte parfois des pointes"),
    w("CORNE", 1, "Pointe osseuse du front", "Attribut du rhinocéros"),
    w("BEC", 2, "Mâchoire sans dents", "Bouche dure de l'oiseau"),
    w("PLUME", 2, "Ce qui couvrait certains théropodes", "Léger duvet"),
    w("CARNIVORE", 2, "Mangeur de viande", "Il chasse les autres"),
    w("HERBIVORE", 2, "Mangeur de feuilles", "Amateur de fougères"),
    w("SQUELETTE", 1, "Montage de la grande salle", "Assemblage des os"),
    w("FOUILLE", 2, "Chantier du paléontologue", "Travail à la truelle"),
    w("METEORITE", 2, "Roche tombée du ciel", "Elle a creusé un cratère"),
    w("MARAIS", 2, "Zone humide et chaude", "Terrain spongieux"),
    w("SAURIEN", 3, "Grand reptile ancien", "Vieux mot de naturaliste"),
    w("CRATERE", 2, "Creux laissé par un choc", "Cuvette lunaire"),
    w("DISPARU", 2, "Qui n'existe plus nulle part", "Effacé du vivant"),
    w("MUSEE", 1, "Il conserve les vitrines", "Sortie scolaire classique"),
  ],
  plants: [
    w("RACINE", 1, "Ancre souterraine", "Elle boit pour la plante"),
    w("FEUILLE", 1, "Panneau solaire vert", "Elle tombe en automne"),
    w("TIGE", 1, "Support qui monte", "Le fleuriste la coupe"),
    w("GRAINE", 1, "Contenu du sachet", "Petit colis d'avenir"),
    w("PETALE", 1, "Pièce colorée de la fleur", "On l'effeuille par jeu"),
    w("POLLEN", 2, "Poudre portée par les abeilles", "Cause d'éternuements d'été"),
    w("TERREAU", 2, "Mélange du rempotage", "Sac lourd de la jardinerie"),
    w("FOUGERE", 2, "Amie de l'ombre, à frondes", "Verdure du sous-bois"),
    w("MOUSSE", 2, "Coussin vert des pierres", "Velours humide du mur"),
    w("CACTUS", 2, "Piquant du désert", "Il garde son eau"),
    w("ORCHIDEE", 2, "Fleur exigeante du rebord", "Elle a un labelle"),
    w("POUSSE", 2, "Premier jet vert", "Elle sort de terre"),
    w("TAILLER", 2, "Couper pour faire repartir", "Travail du sécateur"),
    w("COMPOST", 2, "Déchets de cuisine mûris", "Tas sombre du fond du jardin"),
    w("TULIPE", 1, "Bulbe venu des Pays-Bas", "Fleur en coupe du printemps"),
    w("ROSE", 1, "Fleur à épines", "Vedette de juin"),
    w("LIERRE", 2, "Grimpant des vieux murs", "Persistant qui s'accroche"),
    w("BAMBOU", 2, "Graminée creuse et rapide", "Repas du panda"),
    w("NECTAR", 2, "Récompense sucrée de la fleur", "Les abeilles en font du miel"),
    w("EPINE", 1, "Défense pointue", "Avertissement du rosier"),
    w("ARBUSTE", 2, "Petit ligneux du jardin", "Matière de la haie"),
    w("GREFFE", 3, "Union de deux végétaux", "Technique du verger"),
    w("BULBE", 2, "Réserve enterrée", "À planter en octobre"),
    w("SEVE", 2, "Liquide qui monte au printemps", "Origine du sirop d'érable"),
    w("SERRE", 1, "Abri vitré", "Chaleur pour les semis"),
  ],
  coffee: [
    w("GRAIN", 1, "Ce que l'on torréfie", "Il passe au moulin"),
    w("EXPRESSO", 1, "Petite tasse sous pression", "Base du macchiato"),
    w("NOISETTE", 3, "Petit noir avec un nuage de lait", "Commande brève au comptoir"),
    w("ALLONGE", 2, "Servi avec plus d'eau", "Version longue du petit noir"),
    w("MOKA", 2, "Cafetière italienne", "Port qui a donné son nom"),
    w("ARABICA", 3, "Espèce la plus cultivée", "La plus douce des deux espèces"),
    w("MOULIN", 2, "Il réduit en poudre", "Appareil à manivelle"),
    w("FILTRE", 1, "Cône de papier", "Il retient la mouture"),
    w("BARISTA", 2, "Spécialiste du comptoir", "Il extrait les tasses"),
    w("CAFEINE", 2, "Stimulant du matin", "Raison de la deuxième tasse"),
    w("INFUSER", 2, "Laisser le goût se libérer", "Attendre quatre minutes"),
    w("VAPEUR", 1, "Jet qui fait mousser le lait", "Sortie de la buse"),
    w("TASSE", 1, "Récipient à anse", "Elle repose sur la soucoupe"),
    w("SUCRE", 1, "Morceau qui adoucit", "Deux, s'il vous plaît"),
    w("CREME", 1, "Ajout laitier", "Touche riche"),
    w("AMER", 1, "Goût sans douceur", "Signe d'une extraction trop longue"),
    pn(w("ETHIOPIE", 3, "Berceau de la boisson", "Pays du Yirgacheffe")),
    w("TERRASSE", 1, "On s'y attable dehors", "Rangée de chaises au soleil"),
    w("COMPTOIR", 2, "Le zinc du bistrot", "On y boit debout"),
    w("AROME", 2, "Odeur qui réveille la cuisine", "Elle sort du paquet ouvert"),
    w("DECA", 2, "Version du soir", "Sans le coup de fouet"),
    w("SOUCOUPE", 2, "Petite assiette du dessous", "Elle reçoit la cuillère"),
    w("TORREFIER", 3, "Griller les grains", "Passer au tambour chaud"),
    w("MOUSSE", 2, "Couche aérée sur le lait", "Dessus d'un cappuccino"),
  ],
  space: [
    w("ORBITE", 1, "Trajectoire autour d'un astre", "La station y tourne"),
    w("LUNE", 1, "Astre des marées", "Premier sol foulé hors de chez nous"),
    pn(w("MARS", 1, "Voisine rouillée", "Monde d'Olympus Mons")),
    pn(w("VENUS", 2, "Planète la plus chaude", "Monde à l'effet de serre fou")),
    pn(w("SATURNE", 1, "Géante aux anneaux", "Sixième depuis le Soleil")),
    pn(w("JUPITER", 1, "Plus grosse planète", "Elle porte une grande tache rouge")),
    w("GALAXIE", 1, "Milliards d'étoiles ensemble", "Spirale du ciel profond"),
    w("NEBULEUSE", 2, "Nuage où naissent les astres", "Gaz brillant dans Orion"),
    w("FUSEE", 1, "Engin du lancement", "Elle part sur une colonne de feu"),
    w("LUNAIRE", 2, "Relatif à notre satellite", "Éclipse de pleine phase"),
    w("ECLIPSE", 2, "Passage dans l'ombre", "Bref crépuscule de midi"),
    w("ASTEROIDE", 2, "Rocher de la ceinture", "Corps entre deux planètes"),
    w("COMETE", 2, "Visiteuse glacée à traîne", "Celle de Halley, par exemple"),
    w("SOLAIRE", 1, "Relatif à notre étoile", "Vent venu de la couronne"),
    w("GRAVITE", 1, "Ce qui retient au sol", "Pourquoi la pomme tombe"),
    w("TELESCOPE", 1, "Tube pour observer le ciel", "Instrument de Galilée"),
    w("SPATIAL", 2, "Relatif au cosmos", "Qualifie une agence"),
    w("SATELLITE", 2, "Machine qui tourne autour", "Elle relaie la télévision"),
    w("CRATERE", 2, "Creux d'un impact", "Marque sur un sol lunaire"),
    w("ETOILE", 1, "Fournaise lointaine", "Point brillant de la nuit"),
    w("COSMOS", 2, "L'ensemble de tout", "Sujet de Sagan"),
    w("SONDE", 2, "Engin envoyé explorer", "Voyager en est une"),
    pn(w("APOLLO", 2, "Programme des premiers pas lunaires", "Missions jusqu'à dix-sept")),
    w("ANNEAU", 2, "Ceinture de Saturne", "Cercle de glace et de poussière"),
    w("METEORE", 2, "Traînée dans la nuit", "On lui adresse un vœu"),
  ],
  anatomy: [
    w("COEUR", 1, "Pompe de la poitrine", "Muscle à quatre cavités"),
    w("POUMON", 1, "Organe plein d'alvéoles", "L'un des deux de la respiration"),
    w("FOIE", 1, "Plus gros organe interne", "Il traite ce que l'on boit"),
    w("RATE", 2, "Filtre du sang, à gauche", "Organe longtemps mal-aimé"),
    w("REIN", 1, "Filtre en forme de haricot", "L'un des deux du bas du dos"),
    w("FEMUR", 2, "Plus long des os", "Support de la cuisse"),
    w("TIBIA", 2, "Os du devant de la jambe", "Le plus gros sous le genou"),
    w("CRANE", 1, "Casque naturel", "Boîte du cerveau"),
    w("COLONNE", 1, "Empilement de vertèbres", "Axe du dos"),
    w("NERF", 1, "Fil qui transmet le signal", "Chemin du réflexe"),
    w("ARTERE", 2, "Vaisseau du sang oxygéné", "L'aorte en est une"),
    w("VEINE", 1, "Vaisseau du retour", "On y pique pour un prélèvement"),
    w("MUSCLE", 1, "Tissu qui se contracte", "Le biceps en est un"),
    w("TENDON", 2, "Cordon vers l'os", "Celui d'Achille est célèbre"),
    w("CARTILAGE", 3, "Coussin souple des articulations", "Tissu ferme de l'oreille"),
    w("RETINE", 2, "Couche qui capte la lumière", "Là où vivent les cônes"),
    w("CORNEE", 2, "Vitre devant l'iris", "Surface que l'on opère au laser"),
    w("CERVEAU", 1, "Siège de la pensée", "Organe aux deux hémisphères"),
    w("PANCREAS", 2, "Source de l'insuline", "Glande derrière l'estomac"),
    w("ESTOMAC", 1, "Poche acide", "La digestion y démarre"),
    w("MOELLE", 2, "Partie molle au centre de l'os", "Elle fabrique le sang"),
    w("EMAIL", 2, "Revêtement des dents", "Le plus dur du corps"),
    w("BASSIN", 2, "Ceinture des hanches", "Cuvette osseuse"),
    w("COUDE", 1, "Charnière du bras", "On s'y appuie sur la table"),
    w("PEAU", 1, "Plus grand des organes", "Elle se renouvelle sans cesse"),
  ],
  games: [
    w("NIVEAU", 1, "Étape à terminer", "Il finit sur un drapeau"),
    w("BOSS", 1, "Adversaire de fin d'étape", "Sa barre de vie barre l'écran"),
    w("QUETE", 1, "Mission confiée", "Marqueur sur la carte"),
    w("MANETTE", 1, "On la tient à deux mains", "Boutons et joysticks"),
    w("CONSOLE", 1, "Boîtier sous le téléviseur", "Elle lit disques ou cartouches"),
    w("BORNE", 2, "Machine à pièces de la salle", "Meuble vertical à écran"),
    w("PIXEL", 1, "Petit carré d'écran", "Plus petite unité d'image"),
    w("SPRITE", 3, "Image animée en deux dimensions", "Dessin du personnage d'antan"),
    w("SAUVER", 1, "Garder sa progression", "À faire avant de quitter"),
    w("CORRECTIF", 2, "Réparation livrée plus tard", "Téléchargement qui répare"),
    w("BUTIN", 2, "Récompense ramassée", "Contenu du coffre"),
    w("TRICHE", 1, "Code qui contourne les règles", "Haut, haut, bas, bas"),
    w("LATENCE", 2, "Retard qui gâche la partie", "Ennemie du bon réseau"),
    w("CARTOUCHE", 2, "Support à insérer", "Boîtier des vieilles consoles"),
    w("SUITE", 1, "Épisode numéroté", "Celui avec un deux sur la boîte"),
    w("DEMO", 1, "Extrait d'essai", "Avant-goût gratuit"),
    w("SCORE", 1, "Total des points", "Chiffre du classement"),
    pn(w("TETRIS", 2, "Classique des blocs qui tombent", "Jeu des lignes complètes")),
    w("FLIPPER", 2, "Billes et palettes", "Table à ressort"),
    w("MANCHE", 2, "Partie d'un match", "Elle se joue en deux ou trois"),
    w("AVATAR", 2, "Représentation du joueur", "Figure que l'on dirige"),
    w("ARCADE", 2, "Salle des machines d'antan", "Style de jeu nerveux"),
    w("ECRAN", 1, "Surface d'affichage", "On y regarde tout"),
    w("CLAVIER", 1, "Alternative à la manette", "Touches du joueur sur ordinateur"),
    w("JOUEUR", 1, "Celui qui tient la manette", "Un ou deux, au choix"),
  ],

  volcanoes: [
    w("LAVE", 1, "Roche en fusion à l'air libre", "Elle refroidit en pierre noire"),
    w("MAGMA", 2, "Roche fondue encore sous terre", "Contenu de la chambre profonde"),
    w("CRATERE", 1, "Cuvette au sommet", "Creux au-dessus de la cheminée"),
    w("CALDEIRA", 3, "Vaste dépression d'effondrement", "Grand cirque de Santorin"),
    w("CENDRE", 1, "Elle cloue les avions au sol", "Fine retombée grise"),
    w("PONCE", 3, "Pierre qui flotte sur l'eau", "Roche qui sert à frotter"),
    w("BASALTE", 2, "Roche sombre à grain fin", "Pierre des orgues d'Auvergne"),
    pn(w("ETNA", 2, "Montagne sicilienne souvent active", "Plus haut sommet actif d'Europe")),
    pn(w("VESUVE", 3, "Il a enseveli Pompéi", "Sommet au-dessus de Naples")),
    pn(w("ISLANDE", 2, "Île posée sur une dorsale", "Terre des fissures éruptives")),
    pn(w("POMPEI", 3, "Cité romaine sous les cendres", "Site fouillé près de Naples")),
    w("FISSURE", 3, "Longue crevasse éruptive", "Fente d'où sort un rideau de feu"),
    w("ERUPTION", 2, "Fin d'un long sommeil", "Épisode classé sur une échelle"),
    w("ENDORMI", 2, "Calme mais pas fini", "Entre deux épisodes"),
    w("ETEINT", 2, "Qui n'entrera plus en activité", "Définitivement calme"),
    w("PANACHE", 3, "Colonne qui monte du sommet", "Nuage de gaz et de poussière"),
    w("CONE", 1, "Forme bâtie par les retombées", "Profil classique du relief"),
    w("LAHAR", 4, "Coulée de boue volcanique", "Cendres et eau qui dévalent"),
    w("SOUFRE", 2, "Dépôt jaune autour de la bouche", "Élément à l'odeur piquante"),
    w("GEYSER", 2, "Source chaude qui jaillit", "Jet de vapeur intermittent"),
    w("SEISME", 2, "Secousse du sol", "Elle précède souvent l'activité"),
    w("SCORIE", 4, "Fragment sombre et bulleux", "Débris projeté puis retombé"),
    w("COULEE", 2, "Langue qui descend la pente", "Front rouge qui avance lentement"),
    w("DORSALE", 3, "Chaîne où les plaques s'écartent", "Relief sous-marin de l'Atlantique"),
    w("CHEMINEE", 3, "Conduit vers la surface", "Passage du magma"),
    w("MANTEAU", 3, "Couche sous la croûte", "Origine du matériau fondu"),
    w("PLAQUE", 2, "Morceau rigide de la lithosphère", "Elle glisse de quelques centimètres par an"),
  ],

  "greek-mythology": [
    pn(w("ZEUS", 1, "Roi des dieux de l'Olympe", "Maître de la foudre")),
    pn(w("HERA", 2, "Reine des Olympiens", "Déesse du mariage")),
    pn(w("HADES", 2, "Maître des Enfers", "Frère au lot le plus sombre")),
    pn(w("ATHENA", 1, "Déesse de la sagesse", "Protectrice d'une grande cité")),
    pn(w("APOLLON", 1, "Dieu de la musique et des oracles", "Maître du sanctuaire de Delphes")),
    pn(w("ARTEMIS", 2, "Déesse de la chasse", "Sœur jumelle d'un dieu solaire")),
    pn(w("HERMES", 2, "Messager aux sandales ailées", "Guide des âmes vers le bas")),
    pn(w("ARES", 2, "Dieu des combats", "Équivalent d'un dieu romain guerrier")),
    pn(w("ICARE", 2, "Il a volé trop près du soleil", "Fils d'un artisan crétois")),
    pn(w("MEDUSE", 2, "Gorgone au regard pétrifiant", "Figure à la chevelure de serpents")),
    pn(w("MINOTAURE", 2, "Être à tête de taureau", "Bête enfermée sous Cnossos")),
    pn(w("OLYMPE", 2, "Séjour des douze dieux", "Plus haut mont de Grèce")),
    pn(w("ODYSSEE", 2, "Retour de dix ans", "Seconde épopée d'Homère")),
    pn(w("ILIADE", 3, "Épopée d'un siège de dix ans", "Première épopée d'Homère")),
    pn(w("TROIE", 2, "Cité assiégée par les Achéens", "Ville du cheval de bois")),
    w("ORACLE", 2, "Parole rendue dans un sanctuaire", "Réponse ambiguë d'un dieu"),
    pn(w("DELPHES", 3, "Sanctuaire du Parnasse", "Siège d'une célèbre prophétesse")),
    w("TITAN", 2, "Dieu de l'âge précédent", "Vaincu par les Olympiens"),
    w("CHIMERE", 3, "Monstre composite crachant le feu", "Lion, chèvre et serpent à la fois"),
    w("HYDRE", 3, "Serpent aux têtes multiples", "Monstre du marais de Lerne"),
    pn(w("PEGASE", 2, "Cheval ailé de la légende", "Monture de Bellérophon")),
    w("CENTAURE", 2, "Mi-homme, mi-cheval", "Chiron en était un"),
    w("SIRENE", 2, "Chanteuse qui perd les marins", "On s'attache au mât pour lui résister"),
    w("NECTAR", 2, "Boisson des immortels", "Ce que buvaient les dieux"),
    w("AMBROISIE", 3, "Nourriture des immortels", "Mets réservé aux dieux"),
    w("CYCLOPE", 2, "Géant à un œil", "Berger aveuglé par Ulysse"),
    w("MUSE", 2, "L'une des neuf inspiratrices", "Celle qu'invoque le poète"),
    pn(alt(w("HERACLES", 3, "Héros des douze travaux", "Homme fort de la légende"), "HERAKLES")),
    pn(w("STYX", 3, "Fleuve que passent les morts", "Eau sur laquelle jurent les dieux")),
    pn(w("ULYSSE", 2, "Roi d'Ithaque au long retour", "Inventeur d'une ruse de bois")),
  ],

  "world-war-ii": [
    w("ALLIES", 1, "Coalition de Londres, Moscou et Washington", "Camp vainqueur en 1945"),
    w("AXE", 1, "Allemagne, Italie et Japon réunis", "Camp défait en 1945"),
    pn(w("NORMANDIE", 2, "Région du débarquement de juin 1944", "Côte de l'opération Overlord")),
    pn(w("DUNKERQUE", 2, "Port de l'évacuation de 1940", "Plages vidées par de petits navires")),
    pn(w("ENIGMA", 2, "Machine à chiffrer allemande", "Appareil à rotors finalement percé")),
    ab(w("RADAR", 2, "Détection par échos radio", "Veille aérienne dès 1940")),
    w("CONVOI", 2, "Navires marchands sous escorte", "Formation de l'Atlantique"),
    w("RATION", 1, "Part de nourriture fixée", "Ce qu'un carnet permettait"),
    pn(w("TOBROUK", 3, "Port libyen longtemps assiégé", "Objectif de la guerre du désert")),
    pn(w("ALAMEIN", 3, "Halte ferroviaire d'Égypte, 1942", "Tournant de la campagne d'Afrique")),
    pn(w("MIDWAY", 2, "Atoll du Pacifique, juin 1942", "Bataille de porte-avions")),
    pn(w("ARDENNES", 3, "Forêt d'une contre-offensive de 1944", "Massif tenu en plein hiver")),
    pn(w("YALTA", 3, "Conférence de février 1945", "Rencontre des trois dirigeants")),
    pn(w("POTSDAM", 3, "Conférence de juillet 1945", "Pourparlers près de Berlin")),
    pn(w("VICHY", 3, "Régime installé dans une ville d'eaux", "Gouvernement de 1940 à 1944")),
    w("MAQUIS", 3, "Groupes de résistants ruraux", "Combattants des zones boisées"),
    w("APPEL", 3, "Discours radiodiffusé du 18 juin 1940", "Message lancé de Londres"),
    pn(w("SPITFIRE", 2, "Chasseur britannique monoplace", "Appareil aux ailes elliptiques")),
    sv(w("BOMBE", 2, "Engin largué d'un avion", "Ce que visait la défense passive")),
    sv(w("TORPILLE", 2, "Arme sous-marine autopropulsée", "Tirée par un submersible")),
    sv(w("SIEGE", 2, "Encerclement d'une ville", "Blocus prolongé")),
    sv(w("VICTIME", 3, "Personne tuée ou blessée", "Chiffre d'un bilan sombre")),
    w("ABRI", 1, "Refuge sous les bombardements", "Cave aménagée de la ville"),
    w("TICKET", 2, "Coupon du rationnement", "Papier à détacher du carnet"),
    w("CHAR", 2, "Véhicule blindé à chenilles", "Engin des percées"),
    w("CODE", 2, "Ce que les décrypteurs cassent", "Système de chiffres et de lettres"),
    pn(w("BERLIN", 1, "Capitale prise en mai 1945", "Ville partagée après la guerre")),
    pn(w("JAPON", 2, "Pays qui capitule en septembre 1945", "Archipel du théâtre pacifique")),
    pn(w("ALLEMAGNE", 2, "Pays qui capitule en mai 1945", "État vaincu et occupé")),
    pn(w("CHURCHILL", 3, "Premier ministre britannique dès 1940", "Chef du gouvernement de guerre")),
    w("FRONT", 2, "Ligne où l'on combat", "Est ou ouest, selon l'année"),
    w("PAIX", 1, "Ce qui revient en 1945", "Fin des hostilités"),
  ],

  "general-knowledge": [
    pn(w("PARIS", 1, "Capitale sur la Seine", "Ville du Louvre")),
    pn(w("EVEREST", 2, "Plus haut sommet du monde", "Cime à la frontière du Népal")),
    pn(w("NIL", 2, "Fleuve qui traverse Le Caire", "Long cours d'eau africain")),
    pn(w("SAHARA", 2, "Plus grand désert chaud", "Sables du nord de l'Afrique")),
    w("OXYGENE", 2, "Élément numéro huit", "Gaz nécessaire à la respiration"),
    w("FER", 1, "Métal qui rouille", "Métal du forgeron"),
    w("PIANO", 1, "Instrument à quatre-vingt-huit touches", "Droit ou à queue"),
    w("VIOLON", 2, "Quatre cordes et un archet", "Le plus petit des cordes frottées"),
    w("OCTOGONE", 3, "Figure à huit côtés", "Forme d'un panneau d'arrêt"),
    w("ATLAS", 2, "Recueil de cartes", "Ouvrage plein de frontières"),
    w("BOUSSOLE", 2, "Elle indique le nord magnétique", "Aiguille du randonneur"),
    pn(w("MOZART", 2, "Auteur de La Flûte enchantée", "Prodige né à Salzbourg")),
    pn(w("HAMLET", 3, "Prince danois d'une tragédie", "Rôle d'une scène de cimetière")),
    w("PYRAMIDE", 2, "Forme des tombeaux de Gizeh", "Base carrée et quatre faces"),
    w("MARATHON", 2, "Course de quarante-deux kilomètres", "Épreuve qui clôt les Jeux"),
    w("SIECLE", 1, "Cent ans", "Unité des livres d'histoire"),
    w("DECENNIE", 2, "Dix ans", "Durée des années quatre-vingt-dix"),
    w("ALPHABET", 2, "Suite ordonnée des lettres", "Ce qu'enseigne l'abécédaire"),
    pn(ab(w("UNESCO", 3, "Organisation onusienne pour l'éducation", "Elle tient une liste du patrimoine"))),
    ab(w("ADN", 2, "Molécule de l'hérédité, en bref", "Double hélice, en trois lettres")),
    w("HELIUM", 2, "Gaz qui fait monter les ballons", "Deuxième élément du tableau"),
    w("PINGOUIN", 1, "Oiseau marin des mers froides", "Nageur en habit noir et blanc"),
    w("KANGOUROU", 2, "Marsupial qui bondit", "Animal à poche"),
    pn(w("ESPAGNE", 1, "Pays du musée du Prado", "État au sud des Pyrénées")),
    pn(w("TOKYO", 2, "Capitale du Japon", "Ville des Jeux de 1964")),
    w("ECHECS", 1, "Jeu aux soixante-quatre cases", "Plateau à deux évêques par camp"),
    w("VITAMINE", 2, "Nutriment utile à petite dose", "La C ou la D, par exemple"),
    w("GLACIER", 3, "Fleuve de glace très lent", "Il creuse une vallée en auge"),
    pn(w("LOUVRE", 2, "Musée de la Joconde", "Ancien palais devenu musée")),
  ],

  // Le bank français porte sur la littérature française : c'est ce que promet
  // le préréglage « Littérature française » de l'atelier.
  literature: [
    w("ROMAN", 1, "Récit long en prose", "Livre de fiction complet"),
    w("POESIE", 1, "Art des vers", "Genre de Verlaine"),
    w("THEATRE", 1, "Genre joué sur une scène", "Lieu des trois coups"),
    w("SONNET", 2, "Poème de quatorze vers", "Deux quatrains et deux tercets"),
    w("STROPHE", 2, "Groupe de vers", "Paragraphe d'un poème"),
    w("RIME", 1, "Écho sonore en fin de vers", "Pauvre, suffisante ou riche"),
    w("CONTE", 1, "Récit merveilleux et court", "Genre de Perrault"),
    w("FABLE", 2, "Court récit à morale", "Genre du corbeau et du renard"),
    w("NOUVELLE", 2, "Récit bref en prose", "Plus court qu'un roman"),
    w("PREFACE", 3, "Texte placé avant le premier chapitre", "Avant-propos placé en tête"),
    w("AUTEUR", 1, "Nom imprimé sur la couverture", "Celui qui a écrit le livre"),
    w("ECRIVAIN", 2, "Métier de plume", "Personne de lettres"),
    w("LECTEUR", 2, "Celui qui tourne les pages", "Destinataire du livre"),
    w("INTRIGUE", 2, "Enchaînement des événements", "Ce qui se noue puis se dénoue"),
    w("METAPHORE", 3, "Image sans mot de comparaison", "Figure qui identifie deux choses"),
    w("IRONIE", 3, "Dire le contraire de sa pensée", "Écart entre le dit et le pensé"),
    w("SATIRE", 3, "Moquerie qui vise une cible", "Critique par le ridicule"),
    w("COMEDIE", 2, "Pièce qui finit bien", "Genre destiné à faire rire"),
    w("TRAGEDIE", 2, "Pièce qui finit mal", "Genre du destin funeste"),
    w("RECIT", 2, "Ce que raconte le narrateur", "Histoire rapportée"),
    w("VERS", 1, "Ligne mesurée d'un poème", "Unité rythmique de la poésie"),
    w("CHAPITRE", 1, "Division numérotée d'un ouvrage", "Section entre deux titres"),
    w("LIVRE", 1, "Objet de papier relié", "Ce qu'on emprunte à la bibliothèque"),
    pn(w("HUGO", 2, "Nom des Misérables", "Poète des Contemplations")),
    pn(w("ZOLA", 3, "Nom de Germinal", "Romancier des Rougon-Macquart")),
    pn(w("MOLIERE", 2, "Nom de L'Avare", "Nom du Malade imaginaire")),
    pn(w("CAMUS", 3, "Nom de L'Étranger", "Prix Nobel de 1957")),
    pn(w("PROUST", 3, "Nom de la madeleine", "Nom de la Recherche")),
    pn(w("RIMBAUD", 3, "Poète du Bateau ivre", "Adolescent de Charleville")),
  ],
};

/* ==========================================================================
   Arabic — natural spelling, no diacritics, single words
   ========================================================================== */

const AR: Bank = {
  cats: [
    w("قطة", 1, "حيوان أليف يطارد الفئران", "أليف يجلس على النافذة"),
    w("مواء", 1, "صوت يطلب به الطعام", "نداء عند باب المطبخ"),
    w("خرخرة", 2, "صوت خفيض يدل على الرضا", "اهتزاز هادئ في الحضن"),
    w("مخلب", 1, "ظفر حاد ينسحب إلى الداخل", "عدو الأريكة"),
    w("شارب", 2, "شعر حساس حول الفم", "يقيس به سعة الفتحات"),
    w("ذيل", 1, "ما يوازن الجسم من الخلف", "يرتفع علامة استفهام"),
    w("فراء", 1, "غطاء دافئ يتساقط في الربيع", "ما يبقى على الثياب السوداء"),
    w("فأر", 1, "طريدة صغيرة رمادية", "قارض يخشى المطبخ"),
    w("أسد", 1, "صاحب اللبدة", "رمز الشجاعة في الشعارات"),
    w("نمر", 1, "مفترس مخطط كبير", "فهد البنغال المخطط"),
    w("فهد", 2, "أسرع حيوان بري", "منقط سريع في السافانا"),
    w("قيلولة", 1, "نوم قصير في النهار", "راحة في شعاع الشمس"),
    w("صيد", 2, "تعقب الطريدة", "كمين في الحديقة"),
    w("سنور", 3, "اسم فصيح للأليف المدلل", "لفظ قديم في المعاجم"),
    w("وبر", 3, "شعر ناعم يغطي الجلد", "ما يجمعه المشط"),
    w("براثن", 3, "مخالب المفترس", "ما يقبض به على الطريدة"),
    w("حليب", 1, "شراب أبيض يحبه الصغار", "أول غذاء للمولود"),
    w("سلة", 2, "مكان النوم المضفور", "توضع فيها الوسادة"),
    w("طعام", 1, "ما يوضع في الوعاء", "وجبة الصباح"),
    w("لعبة", 1, "كرة صغيرة تسليه", "ما يلهو به الصغير"),
    w("عين", 1, "تلمع في الظلام", "بؤبؤ يضيق في الضوء"),
    w("لسان", 2, "خشن يستعمله في التنظيف", "به يتذوق ويشرب"),
    w("قفزة", 2, "وثبة إلى الرف العالي", "اندفاع من الساقين الخلفيتين"),
  ],
  dinosaurs: [
    w("أحفورة", 2, "بقايا حفظها الحجر", "ما يخرج من المقلع"),
    w("عظم", 1, "قطعة من الهيكل", "ما يجمعه الحفر"),
    w("جمجمة", 1, "علبة الرأس العظمية", "أبرز ما في الفاترينة"),
    w("أسنان", 1, "ما يمزق به اللحم", "مسننة يغلفها المينا"),
    w("بيضة", 1, "ما يوضع في العش", "بداية داخل قشرة"),
    w("مخلب", 1, "ظفر معقوف حاد", "منجل في إصبع القدم"),
    w("حرشفة", 2, "قشرة جلد الزواحف", "تغطي التمساح"),
    w("زاحف", 2, "حيوان بارد الدم", "من صنف السحالي"),
    w("كهف", 1, "تجويف في الجبل", "مأوى في الصخر"),
    w("عنق", 2, "طويل عند العماليق آكلة النبات", "يصل الرأس بالجسم"),
    w("ذيل", 1, "يوازن المشي", "يحمل أشواكا عند بعضها"),
    w("قرن", 1, "نتوء عظمي في الرأس", "سلاح وحيد القرن"),
    w("منقار", 2, "فم بلا أسنان", "فوهة صلبة للطيور"),
    w("ريش", 2, "غطاء خفيف يكسو الطيور", "ما كان على بعض الثيروبودات"),
    w("عشب", 1, "غذاء آكلات النبات", "أخضر قصير في السهل"),
    w("مفترس", 2, "صياد في قمة السلسلة", "يقتات على غيره"),
    w("انقراض", 2, "زوال نوع إلى الأبد", "نهاية سلالة كاملة"),
    w("متحف", 1, "حيث تعرض الهياكل", "زيارة مدرسية معتادة"),
    w("هيكل", 1, "بناء العظام المجمع", "قوام الجسم الداخلي"),
    w("كهرمان", 3, "صمغ تحجر مع الزمن", "حجر برتقالي دافئ"),
    w("نيزك", 2, "صخرة سقطت من السماء", "سبب فوهة كبيرة"),
    w("مستنقع", 2, "أرض رطبة حارة", "طين وماء راكد"),
    w("عملاق", 2, "ضخم يهتز له الأرض", "هائل الحجم"),
    w("طين", 2, "تراب مبلول يحفظ الآثار", "مادة القوالب"),
  ],
  plants: [
    w("جذر", 1, "مرساة تحت التراب", "يشرب للنبات كله"),
    w("ورقة", 1, "لوح أخضر يصنع الغذاء", "تتساقط في الخريف"),
    w("ساق", 1, "ما يحمل الماء إلى الأعلى", "يقصها بائع الزهور"),
    w("بذرة", 1, "ما يوضع في التراب", "حزمة صغيرة من المستقبل"),
    w("زهرة", 1, "أجمل ما يتفتح", "تقدم في مناسبة"),
    w("لقاح", 2, "غبار تنقله النحلة", "سبب حساسية الربيع"),
    w("تربة", 1, "وسط الزراعة", "أرض الحوض والمشتل"),
    w("سرخس", 3, "نبات الظل ذو السعف", "خضرة تحت الشجر"),
    w("طحلب", 2, "أخضر ينمو على الحجر", "مخمل رطب على الجدار"),
    w("صبار", 2, "شوكي يعيش في الصحراء", "يخزن الماء في لحمه"),
    w("برعم", 2, "زهرة لم تتفتح", "بداية على الغصن"),
    w("تقليم", 2, "قص الأغصان الزائدة", "عمل المقص في الشتاء"),
    w("سماد", 2, "غذاء الأرض", "كيس ثقيل من المشتل"),
    w("شوكة", 1, "دفاع حاد على الساق", "تحذير الورد"),
    w("شجيرة", 2, "نبات خشبي قصير", "مادة السياج"),
    w("بصلة", 2, "خزان تحت الأرض", "تزرع في الخريف"),
    w("عصارة", 2, "سائل يجري في الساق", "أصل شراب القيقب"),
    w("ريحان", 2, "عشب عطري في المطبخ", "يرافق الطماطم"),
    w("نخلة", 1, "شجرة التمر", "رمز الواحة"),
    w("زيتون", 1, "شجرة مباركة وثمرها زيت", "ثمر أخضر أو أسود"),
    w("ياسمين", 2, "زهرة بيضاء عطرة", "عرائش دمشق"),
    w("ورد", 1, "زهرة الحب ذات الشوك", "يقطر منه الماء"),
    w("غصن", 1, "فرع صغير", "يحمل الأوراق"),
    w("حديقة", 1, "مكان النباتات المرتبة", "متنفس أخضر في المدينة"),
    w("سقي", 1, "إعطاء الماء", "عمل الصباح في الشرفة"),
  ],
  coffee: [
    w("حبة", 1, "ما يحمص قبل الطحن", "ثمرة صغيرة في الكيس"),
    w("تحميص", 2, "تعريض الحب للنار", "خطوة تحدد اللون والطعم"),
    w("طحن", 1, "تحويل الحب إلى مسحوق", "ما يسبق التحضير"),
    w("فنجان", 1, "وعاء صغير للشرب", "يوضع على الصحن"),
    w("مطحنة", 2, "أداة بمقبض دوار", "ما يحول الحب مسحوقا"),
    w("مصفاة", 2, "ما يحبس الثفل", "مخروط من الورق"),
    w("كافيين", 2, "منبه الصباح", "سبب الكوب الثاني"),
    w("بخار", 1, "ما يرغي الحليب", "يخرج من الأنبوب المعدني"),
    w("حليب", 1, "إضافة بيضاء", "يخفف الطعم القوي"),
    w("سكر", 1, "ما يحلي الشراب", "مكعب أو ملعقة"),
    w("رغوة", 2, "طبقة هوائية على السطح", "أعلى الكابتشينو"),
    w("مرارة", 2, "طعم غير حلو", "علامة على إفراط في الاستخلاص"),
    w("رائحة", 2, "ما يوقظ المطبخ", "تنبعث عند فتح الكيس"),
    w("ركوة", 2, "إبريق نحاسي صغير", "توضع على الجمر"),
    w("دلة", 2, "إبريق الضيافة الخليجي", "بجانبها الفناجين الصغيرة"),
    w("هيل", 2, "بهار يضاف في الخليج", "حبات عطرة خضراء"),
    pn(w("اليمن", 3, "بلد ميناء المخا", "أول من صدر الشراب تجارة")),
    pn(w("اثيوبيا", 3, "مهد الشجرة الأصلية", "بلد إقليم يرغاتشيف")),
    w("مقهى", 1, "مكان الجلسات والأحاديث", "طاولات وصحف وأحاديث"),
    w("ضيافة", 1, "كرم استقبال الزائر", "تقاليد الترحيب"),
    w("ساخن", 1, "عكس بارد", "يقدم فورا بعد التحضير"),
    w("كوب", 1, "وعاء بمقبض للشرب", "على مكتب الموظف"),
    w("تمر", 1, "يقدم إلى جانب الشراب", "ثمر النخلة الحلو"),
    w("مذاق", 2, "ما يتركه الشراب في الفم", "ما يميز محصولا عن آخر"),
  ],
  space: [
    w("مدار", 1, "مسار حول النجم", "فيه تدور المحطة"),
    w("قمر", 1, "رفيق الليل وسبب المد", "أول سطح وطئناه خارج الأرض"),
    pn(w("مريخ", 1, "الكوكب الأحمر", "عالم أوليمبوس مونس")),
    pn(w("زحل", 1, "صاحب الحلقات", "السادس من الشمس")),
    pn(w("مشتري", 1, "أكبر الكواكب", "عليه بقعة حمراء عظيمة")),
    w("مجرة", 1, "حشد هائل من النجوم", "حلزون في عمق السماء"),
    w("سديم", 2, "سحابة تولد فيها النجوم", "غاز متوهج في الجبار"),
    w("صاروخ", 1, "ما يحمل المركبة للأعلى", "ينطلق على عمود من نار"),
    w("كسوف", 2, "احتجاب الشمس عن الأرض", "ظلام قصير في وضح النهار"),
    w("خسوف", 2, "دخول القمر في الظل", "يحدث في ليلة البدر"),
    w("كويكب", 2, "صخرة تدور في الحزام", "جسم بين المريخ والمشتري"),
    w("نيزك", 2, "خط ضوئي في السماء", "عليه تتمنى الأمنيات"),
    w("شمس", 1, "نجمنا القريب", "مصدر الضوء والدفء"),
    w("جاذبية", 1, "قوة تسحب نحو الأسفل", "سبب سقوط التفاحة"),
    w("تلسكوب", 1, "أنبوب لرصد السماء", "أداة غاليليو"),
    w("مركبة", 2, "ما يقل الرواد", "تلتحم بالمحطة"),
    w("رائد", 1, "من يسافر إلى المدار", "يلبس بذلة بيضاء"),
    w("كوكب", 1, "جسم يدور حول نجم", "ثمانية في نظامنا"),
    w("نجم", 1, "فرن نووي بعيد", "نقطة تلمع في الليل"),
    w("كون", 2, "كل ما هو موجود", "موضوع علم الفلك الأكبر"),
    w("فوهة", 2, "حفرة أثر ارتطام", "علامة على سطح القمر"),
    w("حلقة", 2, "طوق من جليد وغبار", "ما يحيط بزحل"),
    w("مذنب", 2, "زائر جليدي بذيل طويل", "زائر هالي المشهور"),
    pn(w("عطارد", 2, "أقرب الكواكب إلى الشمس", "أصغر الثمانية")),
    pn(w("نبتون", 2, "أبعد الكواكب الثمانية", "عالم أزرق بعيد")),
  ],
  anatomy: [
    w("قلب", 1, "مضخة الصدر", "عضل بأربع حجرات"),
    w("رئة", 1, "عضو مليء بالحويصلات", "إحدى اثنتين للتنفس"),
    w("كبد", 1, "أكبر عضو داخلي", "يعالج ما نشربه"),
    w("طحال", 2, "مصفاة الدم إلى يسار المعدة", "عضو ظلمته الأقوال القديمة"),
    w("كلية", 1, "مصفاة على شكل حبة", "إحدى اثنتين في أسفل الظهر"),
    w("عظم", 1, "قطعة صلبة في الجسم", "يحيط بالنخاع"),
    w("فخذ", 2, "ما بين الورك والركبة", "فيه أطول عظام الجسم"),
    w("عمود", 1, "صف الفقرات", "محور الظهر"),
    w("فقرة", 2, "حلقة في محور الظهر", "بينها أقراص لينة"),
    w("عصب", 1, "خيط ينقل الإشارة", "طريق رد الفعل"),
    w("شريان", 2, "وعاء ينقل الدم المؤكسج", "الأبهر واحد منها"),
    w("وريد", 1, "وعاء العودة", "منه تسحب العينة"),
    w("عضلة", 1, "نسيج ينقبض", "ذات الرأسين إحداها"),
    w("وتر", 2, "حبل يصل العضلة بالعظم", "أشهره يحمل اسم أخيل"),
    w("غضروف", 3, "وسادة لينة في المفصل", "نسيج مرن في الأذن"),
    w("شبكية", 2, "طبقة تستقبل الضوء", "فيها العصي والمخاريط"),
    w("قرنية", 2, "زجاج أمام القزحية", "سطح يعالج بالليزر"),
    w("دماغ", 1, "مركز التفكير", "له نصفان"),
    w("معدة", 1, "كيس الحمض", "فيها يبدأ الهضم"),
    w("نخاع", 2, "لب العظم اللين", "فيه تصنع كريات الدم"),
    w("مينا", 2, "أقسى غلاف في الجسم", "طبقة تحمي السن"),
    w("حوض", 2, "حزام الوركين", "طست من العظم"),
    w("مرفق", 1, "مفصل الذراع", "عليه نتكئ على الطاولة"),
    w("جلد", 1, "أوسع الأعضاء", "يتجدد بلا توقف"),
    w("ركبة", 1, "مفصل بين الفخذ والساق", "يحميها الرباط الصليبي"),
  ],
  games: [
    w("مرحلة", 1, "طور يجب إتمامه", "تنتهي بباب أو راية"),
    w("شاشة", 1, "سطح العرض", "عليها تظهر الصورة"),
    w("لوحة", 2, "أزرار الحروف للتحكم", "بديل ذراع التحكم"),
    w("نقاط", 1, "مجموع ما يحصده اللاعب", "رقم في قائمة المتفوقين"),
    w("لاعب", 1, "من يمسك ذراع التحكم", "واحد أو اثنان"),
    w("فوز", 1, "نهاية سعيدة للمباراة", "ما يسعى إليه الفريقان"),
    w("خسارة", 1, "عكس الظفر بالمباراة", "نتيجة مرة"),
    w("شطرنج", 1, "لعبة الملك والوزير", "رقعة بأربعة وستين مربعا"),
    w("طاولة", 2, "لعبة الزهر واللوح", "تصحبها أحاديث المقهى"),
    w("كرة", 1, "تتدحرج في معظم الملاعب", "جلد منفوخ بالهواء"),
    w("ورق", 2, "أوراق تخلط وتوزع", "فيها الشايب والبنت"),
    w("زهر", 2, "مكعبان منقطان", "يرميهما اللاعب في اللوح"),
    w("دمية", 1, "لعبة الطفل الصغيرة", "تنام إلى جانبه"),
    w("حبل", 1, "أداة قفز في الساحة", "يشد من طرفيه"),
    w("سباق", 1, "منافسة على السرعة", "يفصل بينهما خط النهاية"),
    w("فريق", 1, "مجموعة تلعب معا", "له قميص واحد"),
    w("قاعدة", 1, "شرط يلتزم به الجميع", "تكتب قبل بدء اللعب"),
    w("جائزة", 1, "ما يناله الأول", "كأس أو ميدالية"),
    w("لغز", 1, "ما يحتاج حلا", "أحجية تشغل الفكر"),
    w("حاسوب", 1, "جهاز الألعاب الإلكترونية", "شاشة ولوحة وفأرة"),
    w("مكعب", 2, "لعبة الوجوه الملونة", "شكل بستة وجوه"),
    w("بطولة", 1, "منافسة على الكأس", "أدوار حتى النهائي"),
    w("تسلية", 2, "ما يمضي به الوقت", "لهو خفيف بعد العمل"),
    w("ملعب", 1, "مكان المباراة", "له خطوط وحدود"),
  ],

  volcanoes: [
    w("حمم", 1, "صخر منصهر يسيل على السطح", "يبرد فيصير حجرا أسود"),
    w("صهارة", 2, "صخر منصهر تحت الأرض", "ما يملأ الغرفة العميقة"),
    w("فوهة", 1, "حفرة في القمة", "مخرج الغازات والدخان"),
    w("رماد", 1, "غبار يغلق المطارات", "ما يتساقط بعد الثورة"),
    w("بازلت", 2, "صخر داكن ناعم الحبيبات", "حجر الأعمدة السداسية"),
    w("خفاف", 3, "حجر يطفو على الماء", "يستعمل في فرك الجلد"),
    w("سبج", 4, "زجاج بركاني أسود", "حجر كان يصنع منه النصل"),
    w("بركان", 1, "جبل يقذف الحمم", "فيزوف مثال عليه"),
    w("انفجار", 2, "لحظة القذف العنيف", "بداية عمود الرماد"),
    w("خمود", 3, "سكون بين نشاطين", "هدوء مؤقت لا نهائي"),
    w("صدع", 2, "شق طويل تخرج منه الحمم", "فتحة ممتدة في الأرض"),
    w("كبريت", 2, "عنصر أصفر حول الفتحة", "سبب الرائحة النفاذة"),
    w("نافورة", 3, "عين حارة تقذف الماء", "جيزر أيسلندا مثال"),
    w("زلزال", 1, "اهتزاز الأرض", "يسبق النشاط غالبا"),
    w("صفيحة", 3, "قطعة من الغلاف الصخري", "تتحرك سنتيمترات كل عام"),
    w("وشاح", 3, "طبقة تحت القشرة", "منها يأتي المصهور"),
    w("قشرة", 2, "أعلى طبقات الأرض", "رقيقة تحت المحيطات"),
    w("مخروط", 1, "شكل يتكون بالتراكم", "هيئة الجبل النموذجية"),
    w("دخان", 1, "ما يتصاعد أسود كثيفا", "علامة النشاط من بعيد"),
    w("سحابة", 2, "كتلة تتصاعد فوق القمة", "غاز وغبار في الجو"),
    w("جزيرة", 1, "أرض يحيطها الماء", "قد تنشأ فوق بقعة ساخنة"),
    pn(w("ايسلندا", 3, "جزيرة على حدود صفيحتين", "بلد الجيزرات والشقوق")),
    pn(w("اندونيسيا", 3, "بلد كراكاتوا", "أرخبيل كثير البراكين")),
    pn(w("فيزوف", 3, "جبل طمر بومبي", "قمة فوق خليج نابولي")),
    w("طين", 2, "خليط ماء وتراب يجري في الوادي", "ما يخلفه انصهار الثلج"),
    w("حرارة", 1, "ما يذيب الصخر في العمق", "درجة تقاس بالمئوية"),
    w("صخر", 1, "مادة الجبال", "ما ينكسر إلى حصى"),
  ],

  "greek-mythology": [
    pn(w("زيوس", 1, "كبير آلهة الأولمب", "صاحب الصاعقة")),
    pn(w("هيرا", 2, "ملكة الأولمب", "ربة الزواج")),
    pn(w("هاديس", 2, "سيد العالم السفلي", "من نال أسوأ القسمة")),
    pn(w("اثينا", 1, "ربة الحكمة والصناعة", "حاملة اسم مدينة كبرى")),
    pn(w("ابولو", 1, "رب الموسيقى والنبوءة", "صاحب معبد دلفي")),
    pn(w("ارتميس", 2, "ربة الصيد", "توأم رب الشمس")),
    pn(w("هرمس", 2, "رسول الآلهة", "صاحب النعل المجنح")),
    pn(w("ايكاروس", 2, "طار قريبا من الشمس", "ابن صانع كريتي")),
    pn(w("ميدوسا", 2, "نظرتها تحول إلى حجر", "ذات شعر من أفاعي")),
    pn(w("مينوتور", 2, "مخلوق برأس ثور", "سجين قصر كنوسوس")),
    w("متاهة", 3, "بناء لا يخرج منه داخله", "ممرات متشابكة"),
    pn(w("اولمب", 2, "مقام الآلهة الاثني عشر", "أعلى جبال اليونان")),
    pn(w("اوديسا", 2, "رحلة عودة عشر سنوات", "ملحمة هوميروس الثانية")),
    pn(w("الياذة", 3, "ملحمة حصار طويل", "أول ملحمتي هوميروس")),
    pn(w("طروادة", 2, "مدينة الحصار العشري", "صاحبة الحصان الخشبي")),
    w("كاهن", 2, "من ينقل جواب المعبد", "وسيط بين الناس والرب"),
    pn(w("دلفي", 3, "معبد النبوءة على البرناس", "مقر كاهنة شهيرة")),
    w("تيتان", 2, "إله من الجيل الأقدم", "هزمه أهل الأولمب"),
    w("هيدرا", 3, "أفعى متعددة الرؤوس", "وحش مستنقع ليرنا"),
    pn(w("بيغاسوس", 2, "فرس مجنح في الأسطورة", "مطية بيليروفون")),
    w("قنطور", 3, "نصفه إنسان ونصفه فرس", "خيرون كان منهم"),
    w("حورية", 2, "مغنية تستهوي البحارة", "يشد أوديسيوس نفسه لتجنبها"),
    w("رحيق", 2, "شراب الخالدين", "ما تشربه الآلهة"),
    w("عملاق", 2, "ذو عين واحدة في الحكاية", "راع أعماه أوديسيوس"),
    w("ملحمة", 2, "قصيدة بطولية طويلة", "شكل شعري قديم"),
    w("بطل", 1, "من يقوم بالأعمال الاثني عشر", "من تروى عنه الحكايات"),
    w("اسطورة", 2, "حكاية قديمة عن الآلهة", "ما تناقلته الأجيال"),
    w("معبد", 1, "بيت العبادة بالأعمدة", "بناء البارثينون منه"),
    pn(w("هرقل", 2, "بطل الأعمال الاثني عشر", "قوي الأسطورة اليونانية")),
  ],

  "world-war-ii": [
    w("الحلفاء", 1, "طرف انتصر في ١٩٤٥", "بريطانيا وأمريكا والسوفييت"),
    w("المحور", 1, "ألمانيا وإيطاليا واليابان", "طرف هزم في ١٩٤٥"),
    pn(w("نورماندي", 2, "منطقة إنزال يونيو ١٩٤٤", "ساحل عملية أوفرلورد")),
    pn(w("دونكيرك", 2, "ميناء إخلاء ١٩٤٠", "شواطئ أخلتها قوارب صغيرة")),
    pn(w("العلمين", 3, "موقع معركتي ١٩٤٢ في مصر", "نقطة تحول في شمال أفريقيا")),
    pn(w("طبرق", 3, "ميناء ليبي طال حصاره", "هدف في حرب الصحراء")),
    pn(w("ميدواي", 2, "جزيرة في الهادئ، يونيو ١٩٤٢", "معركة حاملات طائرات")),
    pn(w("يالطا", 3, "مؤتمر شبه جزيرة القرم ١٩٤٥", "لقاء الزعماء الثلاثة")),
    pn(w("بوتسدام", 3, "مؤتمر يوليو ١٩٤٥", "محادثات قرب برلين")),
    w("استسلام", 3, "إعلان وقف القتال", "ما وقع في مايو ١٩٤٥"),
    w("مقاومة", 2, "حركة سرية ضد المحتل", "عمل خلف الخطوط"),
    w("رادار", 2, "جهاز كشف بالأصداء اللاسلكية", "إنذار مبكر من الجو"),
    w("شيفرة", 3, "رموز يفكها الخبراء", "نظام سري للرسائل"),
    sv(w("حصار", 2, "تطويق لإجبار على التسليم", "منع الإمداد عن مدينة")),
    sv(w("قنبلة", 2, "ما يسقط من الطائرة", "ما تخشاه الملاجئ")),
    sv(w("طوربيد", 2, "سلاح يسير تحت الماء", "يطلق من الغواصة")),
    sv(w("ضحية", 3, "من قتل أو جرح", "رقم في حصيلة مؤلمة")),
    w("خنادق", 3, "حفر يتحصن بها الجنود", "خطوط في الطين"),
    w("تجنيد", 3, "ضم الرجال إلى الجيش", "نداء إلى السلاح"),
    w("تقنين", 3, "توزيع الغذاء بحصص", "ما نظمته دفاتر الكوبونات"),
    w("قافلة", 2, "سفن تسير في حماية", "تشكيل يعبر الأطلسي"),
    w("دبابة", 2, "مدرعة مجنزرة", "آلة الاختراقات البرية"),
    w("طائرة", 2, "ما يقاتل في الجو", "مقاتلة أو قاذفة"),
    w("جبهة", 2, "خط المواجهة", "شرقية أو غربية"),
    w("جيش", 1, "قوة مسلحة منظمة", "من يقوده الجنرال"),
    w("سلام", 1, "ما عاد في ١٩٤٥", "نهاية القتال"),
    pn(w("برلين", 2, "عاصمة سقطت في مايو ١٩٤٥", "مدينة قسمت بعد الحرب")),
    pn(w("اليابان", 2, "استسلم في سبتمبر ١٩٤٥", "أرخبيل مسرح الهادئ")),
    pn(w("المانيا", 2, "استسلمت في مايو ١٩٤٥", "دولة هزمت واحتلت")),
    pn(w("تشرشل", 3, "رئيس وزراء بريطانيا من ١٩٤٠", "زعيم حكومة الحرب")),
    w("معاهدة", 2, "وثيقة اتفاق بين الدول", "ما يوقعه المفاوضون"),
    w("انتصار", 2, "ما احتفل به في ١٩٤٥", "نتيجة نهائية للحرب"),
  ],

  "general-knowledge": [
    pn(w("باريس", 1, "عاصمة على نهر السين", "مدينة متحف اللوفر")),
    pn(w("ايفرست", 2, "أعلى قمة في العالم", "قمة على حدود نيبال")),
    pn(w("النيل", 2, "نهر يمر بالقاهرة", "أطول أنهار أفريقيا")),
    w("صحراء", 2, "أرض قليلة المطر", "رمال الشمال الأفريقي"),
    w("اوكسجين", 2, "العنصر الثامن", "غاز لازم للتنفس"),
    w("حديد", 1, "معدن يصدأ بالرطوبة", "مادة صناعة الفولاذ"),
    w("بيانو", 1, "آلة بثمانية وثمانين مفتاحا", "قائم أو ذو جناح"),
    w("كمان", 2, "آلة بأربعة أوتار وقوس", "أصغر آلات القوس"),
    w("اطلس", 2, "مجموعة خرائط في كتاب", "مرجع مليء بالحدود"),
    w("بوصلة", 2, "تشير إلى الشمال المغناطيسي", "إبرة الرحالة"),
    w("هرم", 2, "شكل مقابر الجيزة", "قاعدة مربعة وأربعة أوجه"),
    w("ماراثون", 2, "سباق اثنين وأربعين كيلومترا", "ختام دورة الألعاب"),
    w("قرن", 1, "مئة عام", "وحدة في كتب التاريخ"),
    w("عقد", 1, "عشر سنوات", "مدة التسعينيات"),
    w("ابجدية", 2, "ترتيب الحروف المعروف", "ما يتعلمه المبتدئ"),
    pn(ab(w("يونسكو", 3, "منظمة أممية للتربية والثقافة", "تحفظ قائمة التراث العالمي"))),
    w("هيليوم", 2, "غاز يرفع البالونات", "ثاني عناصر الجدول"),
    w("بطريق", 1, "طائر لا يطير في الجنوب البعيد", "سباح ببدلة سوداء وبيضاء"),
    w("كنغر", 2, "حيوان جيبي يقفز", "رمز حيواني لأستراليا"),
    pn(w("اسبانيا", 1, "بلد متحف برادو", "دولة جنوب جبال البرانس")),
    pn(w("طوكيو", 2, "عاصمة اليابان", "مدينة ألعاب ١٩٦٤")),
    w("شطرنج", 1, "لعبة أربعة وستين مربعا", "رقعة بوزيرين وملكين"),
    w("فيتامين", 2, "مغذ يلزم بمقدار قليل", "مثل جيم ودال"),
    w("قاموس", 1, "كتاب معاني الكلمات", "مرجع مرتب أبجديا"),
    w("خريطة", 1, "رسم للأرض بمقياس", "ورقة فيها الطرق والحدود"),
    w("عاصمة", 1, "مقر الحكم في بلد", "مدينة الوزارات"),
    w("تقويم", 2, "جدول أيام السنة", "ما يعلق على الحائط في يناير"),
    w("جبل", 1, "مرتفع صخري كبير", "ما يقصده المتسلقون"),
  ],

  // البنك العربي يدور حول الأدب العربي، وهو ما يعد به الإعداد الجاهز في الورشة.
  literature: [
    w("رواية", 1, "قصة نثرية طويلة", "عمل سردي مطول"),
    w("قصيدة", 1, "نص شعري موزون", "ما ينظمه صاحب الديوان"),
    w("شعر", 1, "كلام موزون مقفى", "فن الأوزان"),
    w("نثر", 1, "كلام بلا وزن", "ضد المنظوم"),
    w("قافية", 2, "نهاية البيت المتكررة", "حرف الروي وما بعده"),
    w("ديوان", 2, "مجموعة قصائد لمؤلف واحد", "كتاب يجمع المنظوم"),
    w("كاتب", 1, "من يؤلف النصوص", "صاحب القلم"),
    w("مطالعة", 2, "تصفح الكتب للفهم", "ما يفعله محب المكتبات"),
    w("مسرحية", 2, "نص يمثل على خشبة", "عمل من فصول وحوار"),
    w("قصة", 1, "حكاية تروى", "سرد قصير"),
    w("حكاية", 1, "خبر يروى للتسلية", "ما تقصه الجدات"),
    w("بلاغة", 3, "علم حسن التعبير", "فن الإقناع بالكلام"),
    w("استعارة", 3, "تشبيه حذف أحد طرفيه", "مجاز في اللغة"),
    w("تشبيه", 2, "مقارنة بأداة", "قول إن شيئا كالآخر"),
    w("مقالة", 2, "نص نثري قصير في موضوع", "ما ينشر في الصحف"),
    w("ترجمة", 2, "نقل نص إلى لغة أخرى", "عمل الوسيط بين لغتين"),
    w("ناشر", 3, "من يطبع الكتب ويوزعها", "دار تصدر المؤلفات"),
    w("مكتبة", 1, "مكان الكتب المرتبة", "حيث يستعار الكتاب"),
    w("ملحمة", 3, "قصيدة بطولية طويلة", "سرد لأمجاد الأبطال"),
    w("خيال", 2, "ما تصنعه المخيلة", "عكس الواقع"),
    w("شاعر", 1, "ناظم القصيد", "من يقول الموزون"),
    w("بطل", 1, "الشخصية المحورية", "من تدور حوله الأحداث"),
    w("سرد", 2, "طريقة رواية الأحداث", "تتابع الحكي"),
    w("رمز", 3, "علامة تدل على معنى", "إشارة موحية"),
    pn(w("المتنبي", 3, "صاحب الخيل والليل", "أشهر شعراء العربية")),
    pn(w("محفوظ", 3, "روائي مصري نال نوبل", "صاحب الثلاثية")),
    pn(w("جبران", 3, "صاحب النبي", "أديب المهجر اللبناني")),
    pn(w("شوقي", 3, "أمير الشعراء", "صاحب مصرع كليوباترا")),
  ],
};

export const BANKS: Record<PuzzleLanguage, Bank> = { en: EN, fr: FR, ar: AR };

/* ==========================================================================
   Theme metadata
   ========================================================================== */

export interface ThemeMeta {
  /** Taxonomy subject slug (src/content/taxonomy). */
  subject: string;
  /**
   * Taxonomy collection slug where the library has one; otherwise the theme
   * slug, so the puzzle still carries a stable topic.
   */
  collection: string;
  /** Decorative accent key from globals.css `[data-subject]`. */
  decor: string;
  /** "archival" drops the cheerful framing (docs/design-system.md §1). */
  tone: "playful" | "archival";
}

export const THEME_META: Record<PlaygroundTheme, ThemeMeta> = {
  cats: { subject: "biology", collection: "cats", decor: "biology", tone: "playful" },
  dinosaurs: {
    subject: "geology",
    collection: "dinosaurs-and-prehistoric-life",
    decor: "history",
    tone: "playful",
  },
  plants: { subject: "biology", collection: "plants", decor: "biology", tone: "playful" },
  coffee: {
    subject: "chemistry",
    collection: "everyday-chemistry",
    decor: "chemistry",
    tone: "playful",
  },
  space: { subject: "astronomy", collection: "astronomy", decor: "movies", tone: "playful" },
  anatomy: { subject: "biology", collection: "human-anatomy", decor: "biology", tone: "playful" },
  games: { subject: "games", collection: "games", decor: "games", tone: "playful" },
  weather: { subject: "geography", collection: "weather", decor: "chemistry", tone: "playful" },
  volcanoes: { subject: "geology", collection: "volcanoes", decor: "chemistry", tone: "playful" },
  "greek-mythology": {
    subject: "mythology",
    collection: "greek-mythology",
    decor: "literature",
    tone: "playful",
  },
  "world-war-ii": {
    subject: "world-war-ii",
    collection: "ww2-major-battles",
    decor: "history",
    tone: "archival",
  },
  "general-knowledge": {
    subject: "general-knowledge",
    collection: "general-knowledge",
    decor: "literature",
    tone: "playful",
  },
  gemstones: { subject: "geology", collection: "gemstones", decor: "chemistry", tone: "playful" },
  oceans: { subject: "biology", collection: "marine-biology", decor: "biology", tone: "playful" },
  literature: {
    subject: "literature",
    collection: "classic-literature",
    decor: "literature",
    tone: "playful",
  },
  "taylor-swift": {
    subject: "taylor-swift",
    collection: "taylor-swift",
    decor: "psychology",
    tone: "playful",
  },
  "one-direction": {
    subject: "one-direction",
    collection: "one-direction",
    decor: "psychology",
    tone: "playful",
  },
};

/** Puzzle title per language, in the language of the puzzle. */
const THEME_TITLES: Record<PuzzleLanguage, Record<PlaygroundTheme, string>> = {
  en: {
    cats: "Cats",
    dinosaurs: "Dinosaurs",
    plants: "Plants",
    coffee: "Coffee",
    space: "Space",
    anatomy: "The human body",
    games: "Video games",
    weather: "Weather",
    volcanoes: "Volcanoes",
    "greek-mythology": "Greek mythology",
    "world-war-ii": "World War II",
    "general-knowledge": "General knowledge",
    gemstones: "Gemstones",
    oceans: "The oceans",
    literature: "Literature",
    "taylor-swift": "Taylor Swift",
    "one-direction": "One Direction",
  },
  fr: {
    cats: "Chats",
    dinosaurs: "Dinosaures",
    plants: "Plantes",
    coffee: "Café",
    space: "Espace",
    anatomy: "Le corps humain",
    games: "Jeux vidéo",
    weather: "Météo",
    volcanoes: "Volcans",
    "greek-mythology": "Mythologie grecque",
    "world-war-ii": "Seconde Guerre mondiale",
    "general-knowledge": "Culture générale",
    gemstones: "Pierres précieuses",
    oceans: "Les océans",
    literature: "Littérature française",
    "taylor-swift": "Taylor Swift",
    "one-direction": "One Direction",
  },
  ar: {
    cats: "قطط",
    dinosaurs: "ديناصورات",
    plants: "نباتات",
    coffee: "قهوة",
    space: "فضاء",
    anatomy: "جسم الإنسان",
    games: "ألعاب",
    weather: "طقس",
    volcanoes: "براكين",
    "greek-mythology": "الميثولوجيا اليونانية",
    "world-war-ii": "الحرب العالمية الثانية",
    "general-knowledge": "معلومات عامة",
    gemstones: "أحجار كريمة",
    oceans: "المحيطات",
    literature: "الأدب العربي",
    "taylor-swift": "تايلور سويفت",
    "one-direction": "ون دايركشن",
  },
};

export function themeTitle(language: PuzzleLanguage, theme: PlaygroundTheme): string {
  return THEME_TITLES[language][theme];
}

/** Themes with a bank in the given language, in display order. */
export function themesFor(language: PuzzleLanguage): PlaygroundTheme[] {
  return PLAYGROUND_THEMES.filter((theme) => (BANKS[language][theme] ?? []).length > 0);
}

export function bankFor(language: PuzzleLanguage, theme: PlaygroundTheme): BankWord[] {
  return BANKS[language][theme] ?? [];
}

/** Subject slugs that have at least one themed bank in this language. */
export function subjectsFor(language: PuzzleLanguage): string[] {
  const seen: string[] = [];
  for (const theme of themesFor(language)) {
    const { subject } = THEME_META[theme];
    if (!seen.includes(subject)) seen.push(subject);
  }
  return seen;
}

/** Themes of one subject that have a bank in this language. */
export function themesForSubject(
  language: PuzzleLanguage,
  subject: string
): PlaygroundTheme[] {
  return themesFor(language).filter((theme) => THEME_META[theme].subject === subject);
}

/** The theme whose collection slug matches, if it has a bank in this language. */
export function themeForCollection(
  language: PuzzleLanguage,
  collection: string
): PlaygroundTheme | null {
  return (
    themesFor(language).find((theme) => THEME_META[theme].collection === collection) ?? null
  );
}
