import type { SubjectDef } from "./types";

/**
 * The second wave of subjects. Same rules as the other shelves: slugs are
 * globally unique, every name exists in all three languages, and nothing here
 * is referenced by a component — the seed reads it into the database.
 */
export const MORE: SubjectDef[] = [
  {
    slug: "technology",
    section: "learn",
    theme: "technology",
    names: { en: "Technology", fr: "Technologie", ar: "التقنية" },
    descriptions: {
      en: "Machines, code and the people who wired them together.",
      fr: "Machines, code et ceux qui les ont reliés.",
      ar: "آلات وبرمجيات ومن ربط بينها.",
    },
    collections: [
      { slug: "computing-history", names: { en: "Computing history", fr: "Histoire de l'informatique", ar: "تاريخ الحوسبة" } },
      { slug: "the-internet", names: { en: "The internet", fr: "Internet", ar: "الإنترنت" } },
      { slug: "programming", names: { en: "Programming", fr: "Programmation", ar: "البرمجة" } },
      { slug: "hardware", names: { en: "Hardware", fr: "Matériel", ar: "العتاد" } },
      { slug: "cryptography", names: { en: "Cryptography", fr: "Cryptographie", ar: "التعمية" } },
      { slug: "robotics", names: { en: "Robotics", fr: "Robotique", ar: "الروبوتات" } },
      { slug: "tech-companies", names: { en: "Tech companies", fr: "Entreprises tech", ar: "شركات التقنية" } },
    ],
  },
  {
    slug: "space",
    section: "learn",
    theme: "space",
    names: { en: "Space", fr: "Espace", ar: "الفضاء" },
    descriptions: {
      en: "Planets, missions and the long dark between them.",
      fr: "Planètes, missions et le long noir entre elles.",
      ar: "كواكب وبعثات وما بينها من ظلام طويل.",
    },
    collections: [
      { slug: "the-solar-system", names: { en: "The solar system", fr: "Le système solaire", ar: "المجموعة الشمسية" } },
      { slug: "stars-and-galaxies", names: { en: "Stars and galaxies", fr: "Étoiles et galaxies", ar: "النجوم والمجرات" } },
      { slug: "space-missions", names: { en: "Space missions", fr: "Missions spatiales", ar: "البعثات الفضائية" } },
      { slug: "astronauts", names: { en: "Astronauts", fr: "Astronautes", ar: "روّاد الفضاء" } },
      { slug: "telescopes", names: { en: "Telescopes", fr: "Télescopes", ar: "المراصد" } },
      { slug: "cosmology", names: { en: "Cosmology", fr: "Cosmologie", ar: "علم الكون" } },
      { slug: "moons", names: { en: "Moons", fr: "Lunes", ar: "الأقمار" } },
    ],
  },
  {
    slug: "language",
    section: "learn",
    theme: "language",
    names: { en: "Language", fr: "Langue", ar: "اللغة" },
    descriptions: {
      en: "Words, scripts and the rules underneath them.",
      fr: "Mots, écritures et règles cachées.",
      ar: "كلمات وخطوط وقواعد تحتها.",
    },
    collections: [
      { slug: "etymology", names: { en: "Etymology", fr: "Étymologie", ar: "أصل الكلمات" } },
      { slug: "writing-systems", names: { en: "Writing systems", fr: "Systèmes d'écriture", ar: "أنظمة الكتابة" } },
      { slug: "grammar", names: { en: "Grammar", fr: "Grammaire", ar: "النحو" } },
      { slug: "idioms", names: { en: "Idioms", fr: "Expressions idiomatiques", ar: "التعابير الاصطلاحية" } },
      { slug: "loanwords", names: { en: "Loanwords", fr: "Emprunts", ar: "الكلمات الدخيلة" } },
      { slug: "world-languages", names: { en: "World languages", fr: "Langues du monde", ar: "لغات العالم" } },
      { slug: "translation", names: { en: "Translation", fr: "Traduction", ar: "الترجمة" } },
    ],
  },
  {
    slug: "animals",
    section: "know",
    theme: "animals",
    names: { en: "Animals", fr: "Animaux", ar: "الحيوانات" },
    descriptions: {
      en: "Everything with a pulse, sorted roughly by habitat.",
      fr: "Tout ce qui a un pouls, classé par habitat.",
      ar: "كل ما ينبض، مرتَّبًا حسب الموطن.",
    },
    collections: [
      { slug: "mammals", names: { en: "Mammals", fr: "Mammifères", ar: "الثدييات" } },
      { slug: "birds", names: { en: "Birds", fr: "Oiseaux", ar: "الطيور" } },
      { slug: "insects", names: { en: "Insects", fr: "Insectes", ar: "الحشرات" } },
      { slug: "reptiles", names: { en: "Reptiles", fr: "Reptiles", ar: "الزواحف" } },
      { slug: "sea-creatures", names: { en: "Sea creatures", fr: "Créatures marines", ar: "كائنات البحر" } },
      { slug: "animal-behaviour", names: { en: "Animal behaviour", fr: "Comportement animal", ar: "سلوك الحيوان" } },
      { slug: "pets", names: { en: "Pets", fr: "Animaux de compagnie", ar: "الحيوانات الأليفة" } },
    ],
  },
  {
    slug: "food",
    section: "know",
    theme: "food",
    names: { en: "Food", fr: "Cuisine", ar: "الطعام" },
    descriptions: {
      en: "Ingredients, dishes and where they came from.",
      fr: "Ingrédients, plats et leurs origines.",
      ar: "مكوّنات وأطباق وأصولها.",
    },
    collections: [
      { slug: "world-cuisines", names: { en: "World cuisines", fr: "Cuisines du monde", ar: "مطابخ العالم" } },
      { slug: "spices", names: { en: "Spices", fr: "Épices", ar: "التوابل" } },
      { slug: "baking", names: { en: "Baking", fr: "Pâtisserie", ar: "الخَبز" } },
      { slug: "drinks", names: { en: "Drinks", fr: "Boissons", ar: "المشروبات" } },
      { slug: "kitchen-tools", names: { en: "Kitchen tools", fr: "Ustensiles", ar: "أدوات المطبخ" } },
      { slug: "food-history", names: { en: "Food history", fr: "Histoire de l'alimentation", ar: "تاريخ الطعام" } },
      { slug: "street-food", names: { en: "Street food", fr: "Cuisine de rue", ar: "طعام الشارع" } },
    ],
  },
  {
    slug: "movies-and-tv",
    section: "culture",
    theme: "movies",
    names: { en: "Movies and TV", fr: "Cinéma et télévision", ar: "السينما والتلفزيون" },
    descriptions: {
      en: "Screens big and small, and everyone behind them.",
      fr: "Grands et petits écrans, et ceux qui les font.",
      ar: "الشاشات الكبيرة والصغيرة ومن خلفها.",
    },
    collections: [
      { slug: "classic-films", names: { en: "Classic films", fr: "Films classiques", ar: "أفلام كلاسيكية" } },
      { slug: "directors", names: { en: "Directors", fr: "Réalisateurs", ar: "المخرجون" } },
      { slug: "tv-series", names: { en: "TV series", fr: "Séries télévisées", ar: "المسلسلات" } },
      { slug: "animation", names: { en: "Animation", fr: "Animation", ar: "الرسوم المتحركة" } },
      { slug: "film-awards", names: { en: "Film awards", fr: "Récompenses du cinéma", ar: "جوائز السينما" } },
      { slug: "movie-quotes", names: { en: "Famous scenes", fr: "Scènes célèbres", ar: "مشاهد شهيرة" } },
      { slug: "french-cinema", names: { en: "French cinema", fr: "Cinéma français", ar: "السينما الفرنسية" } },
      { slug: "arab-cinema", names: { en: "Arab cinema", fr: "Cinéma arabe", ar: "السينما العربية" } },
    ],
  },
  {
    slug: "art",
    section: "culture",
    theme: "art",
    names: { en: "Art", fr: "Art", ar: "الفن" },
    descriptions: {
      en: "Paint, stone, movements and museums.",
      fr: "Peinture, pierre, mouvements et musées.",
      ar: "ألوان وحجر ومدارس ومتاحف.",
    },
    collections: [
      { slug: "painting", names: { en: "Painting", fr: "Peinture", ar: "التصوير" } },
      { slug: "sculpture", names: { en: "Sculpture", fr: "Sculpture", ar: "النحت" } },
      { slug: "art-movements", names: { en: "Art movements", fr: "Mouvements artistiques", ar: "المدارس الفنية" } },
      { slug: "famous-artists", names: { en: "Famous artists", fr: "Artistes célèbres", ar: "فنانون مشهورون" } },
      { slug: "museums", names: { en: "Museums", fr: "Musées", ar: "المتاحف" } },
      { slug: "islamic-art", names: { en: "Islamic art", fr: "Art islamique", ar: "الفن الإسلامي" } },
      { slug: "photography", names: { en: "Photography", fr: "Photographie", ar: "التصوير الفوتوغرافي" } },
    ],
  },
  {
    slug: "internet-culture",
    section: "culture",
    theme: "internet",
    names: { en: "Internet culture", fr: "Culture Internet", ar: "ثقافة الإنترنت" },
    descriptions: {
      en: "Memes, forums and the shorthand of being online.",
      fr: "Mèmes, forums et le jargon d'être en ligne.",
      ar: "الميمات والمنتديات ولغة الإنترنت المختصرة.",
    },
    collections: [
      { slug: "memes", names: { en: "Memes", fr: "Mèmes", ar: "الميمات" } },
      { slug: "early-web", names: { en: "The early web", fr: "Les débuts du web", ar: "الويب المبكّر" } },
      { slug: "social-platforms", names: { en: "Social platforms", fr: "Réseaux sociaux", ar: "منصات التواصل" } },
      { slug: "online-slang", names: { en: "Online slang", fr: "Argot en ligne", ar: "لغة الإنترنت" } },
      { slug: "creators", names: { en: "Creators", fr: "Créateurs", ar: "صنّاع المحتوى" } },
      { slug: "internet-history", names: { en: "Internet history", fr: "Histoire d'Internet", ar: "تاريخ الإنترنت" } },
    ],
  },
  {
    slug: "the-2000s",
    section: "culture",
    theme: "y2k",
    names: { en: "The 2000s", fr: "Les années 2000", ar: "الألفينات" },
    descriptions: {
      en: "Flip phones, frosted tips and burned CDs.",
      fr: "Téléphones à clapet, mèches décolorées et CD gravés.",
      ar: "هواتف قابلة للطي وأقراص منسوخة.",
    },
    collections: [
      { slug: "2000s-music", names: { en: "2000s music", fr: "Musique des années 2000", ar: "موسيقى الألفينات" } },
      { slug: "2000s-tv", names: { en: "2000s television", fr: "Télévision des années 2000", ar: "تلفزيون الألفينات" } },
      { slug: "2000s-tech", names: { en: "2000s gadgets", fr: "Gadgets des années 2000", ar: "أجهزة الألفينات" } },
      { slug: "2000s-fashion", names: { en: "2000s fashion", fr: "Mode des années 2000", ar: "موضة الألفينات" } },
      { slug: "2000s-games", names: { en: "2000s games", fr: "Jeux des années 2000", ar: "ألعاب الألفينات" } },
    ],
  },
  {
    slug: "the-2010s",
    section: "culture",
    theme: "y2k",
    names: { en: "The 2010s", fr: "Les années 2010", ar: "عشرينات الألفية" },
    descriptions: {
      en: "Streaming, smartphones and the decade of the feed.",
      fr: "Streaming, smartphones et la décennie du fil d'actualité.",
      ar: "البث والهواتف الذكية وعقد التغذية الإخبارية.",
    },
    collections: [
      { slug: "2010s-music", names: { en: "2010s music", fr: "Musique des années 2010", ar: "موسيقى العقد الثاني" } },
      { slug: "2010s-tv", names: { en: "2010s television", fr: "Télévision des années 2010", ar: "تلفزيون العقد الثاني" } },
      { slug: "2010s-internet", names: { en: "2010s internet", fr: "Internet des années 2010", ar: "إنترنت العقد الثاني" } },
      { slug: "2010s-games", names: { en: "2010s games", fr: "Jeux des années 2010", ar: "ألعاب العقد الثاني" } },
      { slug: "2010s-film", names: { en: "2010s film", fr: "Cinéma des années 2010", ar: "سينما العقد الثاني" } },
    ],
  },
  {
    slug: "morocco",
    section: "culture",
    theme: "morocco",
    names: { en: "Morocco", fr: "Maroc", ar: "المغرب" },
    descriptions: {
      en: "Cities, crafts, landscapes and language of the far west.",
      fr: "Villes, artisanat, paysages et langues de l'extrême occident.",
      ar: "مدن وحرف ومناظر ولغات المغرب الأقصى.",
    },
    collections: [
      { slug: "moroccan-cities", names: { en: "Moroccan cities", fr: "Villes marocaines", ar: "مدن مغربية" } },
      { slug: "moroccan-cuisine", names: { en: "Moroccan cuisine", fr: "Cuisine marocaine", ar: "المطبخ المغربي" } },
      { slug: "moroccan-crafts", names: { en: "Crafts and design", fr: "Artisanat et design", ar: "الحرف والتصميم" } },
      { slug: "amazigh-culture", names: { en: "Amazigh culture", fr: "Culture amazighe", ar: "الثقافة الأمازيغية" } },
      { slug: "moroccan-landscapes", names: { en: "Landscapes", fr: "Paysages", ar: "المناظر الطبيعية" } },
      { slug: "moroccan-music", names: { en: "Moroccan music", fr: "Musique marocaine", ar: "الموسيقى المغربية" } },
    ],
  },
  {
    slug: "arab-world",
    section: "culture",
    theme: "arabworld",
    names: { en: "The Arab world", fr: "Le monde arabe", ar: "العالم العربي" },
    descriptions: {
      en: "Twenty-odd countries, one written language, many spoken ones.",
      fr: "Une vingtaine de pays, une langue écrite, beaucoup de parlers.",
      ar: "أكثر من عشرين بلدًا، لغة مكتوبة واحدة ولهجات كثيرة.",
    },
    collections: [
      { slug: "arab-capitals", names: { en: "Capitals", fr: "Capitales", ar: "العواصم" } },
      { slug: "arab-history", names: { en: "History", fr: "Histoire", ar: "التاريخ" } },
      { slug: "arab-music", names: { en: "Music", fr: "Musique", ar: "الموسيقى" } },
      { slug: "arab-cuisine", names: { en: "Cuisine", fr: "Cuisine", ar: "المطبخ" } },
      { slug: "arabic-dialects", names: { en: "Dialects", fr: "Dialectes", ar: "اللهجات" } },
      { slug: "arab-scientists", names: { en: "Scientists and scholars", fr: "Savants", ar: "العلماء" } },
    ],
  },
  {
    slug: "french-culture",
    section: "culture",
    theme: "frenchculture",
    names: { en: "French culture", fr: "Culture française", ar: "الثقافة الفرنسية" },
    descriptions: {
      en: "Table, street and stage, from Paris outwards.",
      fr: "La table, la rue et la scène, de Paris vers ailleurs.",
      ar: "المائدة والشارع والمسرح، من باريس وما حولها.",
    },
    collections: [
      { slug: "french-cuisine", names: { en: "French cuisine", fr: "Cuisine française", ar: "المطبخ الفرنسي" } },
      { slug: "french-regions", names: { en: "Regions", fr: "Régions", ar: "الأقاليم" } },
      { slug: "french-expressions", names: { en: "Expressions", fr: "Expressions", ar: "التعابير" } },
      { slug: "french-music", names: { en: "French music", fr: "Musique française", ar: "الموسيقى الفرنسية" } },
      { slug: "french-history-culture", names: { en: "Landmarks of history", fr: "Repères historiques", ar: "محطات تاريخية" } },
      { slug: "french-fashion", names: { en: "Fashion", fr: "Mode", ar: "الموضة" } },
    ],
  },
];
